import { useState, useEffect, useCallback, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { LocalNotifications } from '@capacitor/local-notifications';
import { FirebaseAuthentication } from '@capacitor-firebase/authentication';
import { GoogleAuth } from '@codetrix-studio/capacitor-google-auth';

import BodyPredictor from './BodyPredictor';
import PRTracker from './PRTracker';
import BMICalculator from './BMICalculator';
import BodyMeasurements from './BodyMeasurements';
import AiCoach from './AiCoach';
import ProfileSetup from './ProfileSetup';
import type { UserProfile } from './ProfileSetup';

type ViewType = 'login' | 'home' | 'coach' | 'train' | 'stats' | 'board' | 'journal' | 'sleep' | 'predictor' | 'profile' | 'pr' | 'bmi' | 'measurements';

interface Toast {
  id: number;
  message: string;
  type: 'success' | 'error' | 'info' | 'warning';
}

interface JournalEntry {
  id: number;
  date: string;
  time: string;
  timestamp: number;
  text: string;
  mood: string;
  steps?: number;
  heartRate?: number;
  autoGenerated?: boolean;
}

export interface FitDataType {
  steps: { today: number; weeklyData: number[]; goal: number };
  heartRate: { current: number; avg: number; max: number; min: number };
  sleep: { hours: string; quality: string };
}

interface SleepStage {
  stage: 'deep' | 'light' | 'rem' | 'awake';
  minutes: number;
  color: string;
  label: string;
}

interface NightSleepData {
  date: string;
  totalHours: number;
  qualityScore: number;
  stages: SleepStage[];
}

interface WeightEntry {
  date: string;
  weight: number;
}

interface WorkoutExercise {
  name: string;
  sets: number;
  reps: number;
  weight: number;
  unit: 'kg' | 'lbs' | 'bw';
  muscle: string;
}

interface WorkoutLog {
  id: number;
  date: string;
  dateLabel: string;
  timestamp: number;
  exercises: WorkoutExercise[];
  duration: number;
  notes: string;
  voiceText: string;
}

interface NavItem { id: ViewType; label: string; icon: string; }

const MOODS = ['😊','💪','😴','🔥','😤','🧘','😰','🏆'];

const NAV_ITEMS: NavItem[] = [
  { id: 'home',    label: 'HOME',    icon: '⚡' },
  { id: 'coach',   label: 'COACH',   icon: '🤖' },
  { id: 'train',   label: 'TRAIN',   icon: '🏋️' },
  { id: 'stats',   label: 'STATS',   icon: '📊' },
  { id: 'board',   label: 'BOARD',   icon: '🎯' },
  { id: 'journal', label: 'JOURNAL', icon: '📝' },
  { id: 'predictor', label: 'PREDICT', icon: '🔮' },
  { id: 'sleep',   label: 'SLEEP',   icon: '🌙' },
  { id: 'pr', label: 'PR', icon: '🏆' },
  { id: 'bmi', label: 'BMI', icon: '⚖️' },
  { id: 'measurements', label: 'BODY', icon: '📏' },
];

const AUTO_REFRESH_MS = 30_000;
const HOURLY_MS = 60 * 60_000;

// ── Storage ──
const WEIGHT_KEY = 'hardreps_weight_log';
const WORKOUT_KEY = 'hardreps_workout_log';
const WORKOUT_PLAN_KEY = 'hardreps_workout_plan';

const loadWeights = (): WeightEntry[] => { try { return JSON.parse(localStorage.getItem(WEIGHT_KEY)||'[]'); } catch { return []; } };
const saveWeights = (e: WeightEntry[]) => { try { localStorage.setItem(WEIGHT_KEY, JSON.stringify(e)); } catch { /* */ } };
const loadWorkouts = (): WorkoutLog[] => { try { return JSON.parse(localStorage.getItem(WORKOUT_KEY)||'[]'); } catch { return []; } };
const saveWorkouts = (w: WorkoutLog[]) => { try { localStorage.setItem(WORKOUT_KEY, JSON.stringify(w)); } catch { /* */ } };
const loadWorkoutPlan = () => { try { return JSON.parse(localStorage.getItem(WORKOUT_PLAN_KEY)||'null'); } catch { return null; } };
const saveWorkoutPlan = (plan: { time: string; workout: string }) => { try { localStorage.setItem(WORKOUT_PLAN_KEY, JSON.stringify(plan)); } catch { /* */ } };
const todayStr = () => new Date().toISOString().slice(0, 10);

const scheduleWorkoutReminder = async (timeStr: string, workoutDesc: string) => {
  try {
    await LocalNotifications.cancel({ notifications: [{ id: 101 }, { id: 102 }] });
    const now = new Date();
    const evening = new Date();
    evening.setHours(18, 0, 0, 0);
    if (evening <= now) evening.setDate(evening.getDate() + 1);
    const [hour, minute] = timeStr.split(':').map(Number);
    const workoutTime = new Date();
    workoutTime.setHours(hour, minute, 0, 0);
    if (workoutTime <= now) workoutTime.setDate(workoutTime.getDate() + 1);
    await LocalNotifications.schedule({
      notifications: [
        {
          id: 101,
          title: '💪 Kal Ka Workout Plan Karo!',
          body: 'Kal kitne baje aur kya workout karoge? App mein set karo!',
          schedule: { at: evening, repeats: true, every: 'day' as any },
          extra: { type: 'planning' },
        },
        {
          id: 102,
          title: '🔥 Workout Time!',
          body: `Aaj ka plan: ${workoutDesc} — koi excuse nahi! 💪`,
          schedule: { at: workoutTime, repeats: true, every: 'day' as any },
          extra: { type: 'reminder' },
        },
      ],
    });
    return true;
  } catch (e) { console.error(e); return false; }
};

const playSound = (type: 'click' | 'success' | 'sync' | 'notify') => {
  try {
    const ctx = new (window.AudioContext || (window as any).webkitAudioContext)();
    const osc = ctx.createOscillator();
    const gain = ctx.createGain();
    osc.connect(gain); gain.connect(ctx.destination);
    const now = ctx.currentTime;
    switch (type) {
      case 'click':
        osc.frequency.value = 800;
        gain.gain.setValueAtTime(0.12, now);
        gain.gain.exponentialRampToValueAtTime(0.001, now + 0.08);
        osc.start(now); osc.stop(now + 0.08); break;
      case 'success':
        osc.frequency.setValueAtTime(523, now);
        osc.frequency.setValueAtTime(659, now + 0.08);
        osc.frequency.setValueAtTime(784, now + 0.16);
        gain.gain.setValueAtTime(0.15, now);
        gain.gain.exponentialRampToValueAtTime(0.001, now + 0.3);
        osc.start(now); osc.stop(now + 0.3); break;
      case 'sync':
        osc.frequency.setValueAtTime(400, now);
        osc.frequency.linearRampToValueAtTime(900, now + 0.15);
        gain.gain.setValueAtTime(0.1, now);
        gain.gain.exponentialRampToValueAtTime(0.001, now + 0.2);
        osc.start(now); osc.stop(now + 0.2); break;
      case 'notify':
        osc.frequency.setValueAtTime(880, now);
        osc.frequency.setValueAtTime(1100, now + 0.1);
        osc.frequency.setValueAtTime(880, now + 0.2);
        gain.gain.setValueAtTime(0.15, now);
        gain.gain.exponentialRampToValueAtTime(0.001, now + 0.3);
        osc.start(now); osc.stop(now + 0.3); break;
    }
  } catch { /* silent */ }
};

const parseVoiceWorkout = (text: string): WorkoutExercise[] => {
  const exercises: WorkoutExercise[] = [];
  const lower = text.toLowerCase();
  const muscleMap: Record<string, string> = {
    'bench': 'Chest', 'chest': 'Chest', 'push up': 'Chest', 'pushup': 'Chest',
    'pull up': 'Back', 'pullup': 'Back', 'deadlift': 'Back', 'row': 'Back', 'lat': 'Back',
    'squat': 'Legs', 'leg': 'Legs', 'lunge': 'Legs', 'calf': 'Legs',
    'shoulder': 'Shoulder', 'overhead': 'Shoulder', 'ohp': 'Shoulder', 'lateral': 'Shoulder',
    'curl': 'Biceps', 'bicep': 'Biceps',
    'tricep': 'Triceps', 'dip': 'Triceps', 'extension': 'Triceps',
    'plank': 'Core', 'crunch': 'Core', 'ab': 'Core', 'core': 'Core',
    'run': 'Cardio', 'walk': 'Cardio', 'jump': 'Cardio', 'burpee': 'Cardio',
  };
  const patterns = [
    /(\d+)\s*sets?\s+(\d+)\s*reps?\s+(.+?)\s+(\d+)\s*kg/gi,
    /(\d+)\s*sets?\s+(.+?)\s+(\d+)\s*reps?\s+(\d+)\s*kg/gi,
    /(.+?)\s+(\d+)\s*sets?\s+(\d+)\s*reps?\s+(\d+)\s*kg/gi,
    /(\d+)\s*x\s*(\d+)\s+(.+?)\s+(\d+)\s*kg/gi,
    /(.+?)\s+(\d+)\s*x\s*(\d+)\s+(\d+)\s*kg/gi,
  ];
  let matched = false;
  for (const pattern of patterns) {
    let m;
    pattern.lastIndex = 0;
    while ((m = pattern.exec(lower)) !== null) {
      const groups = m.slice(1).filter(Boolean);
      if (groups.length >= 3) {
        const nums = groups.filter(g => /^\d+$/.test(g)).map(Number);
        const name = groups.find(g => /[a-z]/.test(g)) || 'Exercise';
        if (nums.length >= 2) {
          const muscle = Object.entries(muscleMap).find(([k]) => name.includes(k))?.[1] || 'Full Body';
          exercises.push({ name: name.replace(/\b\w/g, c => c.toUpperCase()).trim(), sets: nums[0] || 3, reps: nums[1] || 10, weight: nums[2] || 0, unit: 'kg', muscle });
          matched = true;
        }
      }
    }
    if (matched) break;
  }
  if (!matched) {
    const simplePattern = /(\d+)\s+([a-z\s]+?)(?:\s|$|,|aur|and)/gi;
    let m2;
    while ((m2 = simplePattern.exec(lower)) !== null) {
      const reps = parseInt(m2[1]);
      const name = m2[2].trim();
      if (reps > 0 && name.length > 2) {
        const muscle = Object.entries(muscleMap).find(([k]) => name.includes(k))?.[1] || 'Full Body';
        exercises.push({ name: name.replace(/\b\w/g, c => c.toUpperCase()), sets: 1, reps, weight: 0, unit: 'bw', muscle });
      }
    }
  }
  return exercises.length > 0 ? exercises : [{ name: text.replace(/\b\w/g, c => c.toUpperCase()).slice(0, 30), sets: 3, reps: 10, weight: 0, unit: 'bw', muscle: 'Full Body' }];
};

const analyzeWorkout = (exercises: WorkoutExercise[]): string => {
  if (!exercises.length) return '';
  const muscles = [...new Set(exercises.map(e => e.muscle))];
  const totalSets = exercises.reduce((a, e) => a + e.sets, 0);
  const totalReps = exercises.reduce((a, e) => a + e.sets * e.reps, 0);
  const hasWeight = exercises.some(e => e.weight > 0);
  let analysis = `💪 ${exercises.length} exercise${exercises.length > 1 ? 's' : ''} detected!\n`;
  analysis += `📊 Total: ${totalSets} sets, ${totalReps} reps\n`;
  analysis += `🎯 Muscles: ${muscles.join(', ')}\n`;
  if (hasWeight) analysis += `🏋️ Weighted exercises included\n`;
  if (muscles.includes('Chest') && muscles.includes('Back')) analysis += `\n✅ Balanced push-pull workout!`;
  else if (muscles.length === 1) analysis += `\n💡 Try adding complementary muscle groups next time!`;
  if (totalSets > 15) analysis += `\n🔥 High volume workout — great effort!`;
  else if (totalSets < 6) analysis += `\n💡 Consider adding more sets for better results.`;
  return analysis;
};

const requestNotificationPermission = async () => {
  try {
    const result = await LocalNotifications.requestPermissions();
    return result.display === 'granted';
  } catch {
    return false;
  }
};

const sendNotification = (title: string, body: string) => {
  LocalNotifications.schedule({
    notifications: [{
      id: Math.floor(Math.random() * 10000),
      title,
      body,
      schedule: { at: new Date(Date.now() + 100) },
    }]
  }).catch(() => {});
};

const fetchGoogleFitData = async (accessToken: string) => {
  const now = Date.now();
  const week = 7 * 24 * 60 * 60 * 1000;
  const headers: Record<string, string> = { Authorization: `Bearer ${accessToken}`, 'Content-Type': 'application/json' };
  const post = (url: string, body: object) => fetch(url, { method: 'POST', headers, body: JSON.stringify(body) });
  const [stepsRes, hrRes, sleepRes] = await Promise.all([
    post('https://www.googleapis.com/fitness/v1/users/me/dataset:aggregate', { aggregateBy: [{ dataTypeName: 'com.google.step_count.delta', dataSourceId: 'derived:com.google.step_count.delta:com.google.android.gms:merge_step_deltas' }], bucketByTime: { durationMillis: 86_400_000 }, startTimeMillis: now - week, endTimeMillis: now }),
    post('https://www.googleapis.com/fitness/v1/users/me/dataset:aggregate', { aggregateBy: [{ dataTypeName: 'com.google.heart_rate.bpm', dataSourceId: 'derived:com.google.heart_rate.bpm:com.google.android.gms:merge_heart_rate_bpm' }], bucketByTime: { durationMillis: 86_400_000 }, startTimeMillis: now - week, endTimeMillis: now }),
    post('https://www.googleapis.com/fitness/v1/users/me/dataset:aggregate', { aggregateBy: [{ dataTypeName: 'com.google.sleep.segment' }], bucketBySession: {}, startTimeMillis: now - week, endTimeMillis: now }),
  ]);
  if (!stepsRes.ok) throw new Error(`Steps API ${stepsRes.status}`);
  if (!hrRes.ok) throw new Error(`HR API ${hrRes.status}`);
  if (!sleepRes.ok) throw new Error(`Sleep API ${sleepRes.status}`);
  return { steps: await stepsRes.json(), heartRate: await hrRes.json(), sleepStages: await sleepRes.json() };
};

const parseSteps = (data: any) => {
  if (!data?.bucket) return { today: 0, weeklyData: Array(7).fill(0) as number[], goal: 10_000 };
  const raw = data.bucket.map((b: any) => b.dataset?.[0]?.point?.[0]?.value?.[0]?.intVal ?? 0);
  while (raw.length < 7) raw.unshift(0);
  const weeklyData = raw.slice(-7);
  return { today: weeklyData[weeklyData.length - 1] || 0, weeklyData, goal: 10_000 };
};

const parseHeartRate = (data: any) => {
  const empty = { current: 0, avg: 0, max: 0, min: 0 };
  if (!data?.bucket) return empty;
  const allDay: number[] = []; const todayR: number[] = [];
  data.bucket.forEach((b: any, idx: number) => {
    for (const p of (b.dataset?.[0]?.point ?? [])) {
      const v = p.value?.[0]?.fpVal;
      if (v == null || v <= 0 || v > 250) continue;
      allDay.push(Math.round(v));
      if (idx === data.bucket.length - 1) todayR.push(Math.round(v));
    }
  });
  if (allDay.length === 0) return empty;
  const avg = Math.round(allDay.reduce((a, b) => a + b, 0) / allDay.length);
  return { current: todayR.length > 0 ? todayR[todayR.length - 1] : avg, avg, max: Math.max(...allDay), min: Math.min(...allDay) };
};

const parseSleepStages = (data: any): NightSleepData[] => {
  if (!data?.bucket) return generateMockSleepData();
  const nights: NightSleepData[] = [];
  for (const bucket of data.bucket) {
    const points = bucket.dataset?.[0]?.point ?? [];
    if (points.length === 0) continue;
    let deep = 0, light = 0, rem = 0, awake = 0;
    for (const pt of points) {
      const type = pt.value?.[0]?.intVal; if (type == null) continue;
      let minutes = 0;
      try { minutes = Math.round(Number((BigInt(pt.endTimeNanos) - BigInt(pt.startTimeNanos)) / BigInt(1_000_000)) / 60); } catch { continue; }
      if (minutes < 0 || minutes > 600) continue;
      switch (type) {
        case 5: case 4: deep += minutes; break;
        case 1: awake += minutes; break;
        case 2: light += minutes; break;
        case 6: rem += minutes; break;
        default: awake += minutes; break;
      }
    }
    const total = deep + light + rem + awake;
    if (total < 30) continue;
    const qualityScore = Math.min(100, Math.round((deep/total)*40+(rem/total)*30+(light/total)*20+Math.max(0,1-awake/total)*10));
    nights.push({ date: new Date(Number(bucket.startTimeMillis)).toLocaleDateString('en-US', { weekday:'short', day:'numeric', month:'short' }), totalHours: parseFloat((total/60).toFixed(1)), qualityScore, stages: [{ stage:'deep', minutes:deep, color:'#4C6EF5', label:'Deep' }, { stage:'rem', minutes:rem, color:'#7C3AED', label:'REM' }, { stage:'light', minutes:light, color:'#6B8EFF', label:'Light' }, { stage:'awake', minutes:awake, color:'#FF6B6B', label:'Awake' }] });
  }
  return nights.length > 0 ? nights : generateMockSleepData();
};

const generateMockSleepData = (): NightSleepData[] =>
  Array.from({length:7}).map((_,i) => {
    const d=new Date(); d.setDate(d.getDate()-6+i);
    const day=d.toLocaleDateString('en-IN',{weekday:'short',day:'numeric',month:'short'});
    const deep=60+Math.round(Math.random()*40), rem=50+Math.round(Math.random()*30);
    const light=120+Math.round(Math.random()*60), awake=10+Math.round(Math.random()*20);
    const total=deep+rem+light+awake;
    return { date:day.replace(',',''), totalHours:parseFloat((total/60).toFixed(1)), qualityScore: Math.min(100,Math.round((deep/total)*40+(rem/total)*30+(light/total)*20+(1-awake/total)*10)), stages: [{ stage:'deep', minutes:deep, color:'#4C6EF5', label:'Deep' }, { stage:'rem', minutes:rem, color:'#7C3AED', label:'REM' }, { stage:'light', minutes:light, color:'#6B8EFF', label:'Light' }, { stage:'awake', minutes:awake, color:'#FF6B6B', label:'Awake' }] };
  });

const sleepQualityMeta = (score: number) => {
  if (score >= 80) return { label:'Excellent', color:'#22c55e' };
  if (score >= 65) return { label:'Good', color:'#E8FF6B' };
  if (score >= 45) return { label:'Fair', color:'#FBBC04' };
  return { label:'Poor', color:'#FF6B6B' };
};

const deriveSleepSummary = (nights: NightSleepData[]) => {
  if (!nights.length) return { hours:'0', quality:'No data' };
  const last = nights[nights.length-1];
  return { hours:String(last.totalHours), quality:sleepQualityMeta(last.qualityScore).label };
};

const JOURNAL_KEY = 'hardreps_journals_v3';
const loadJournals = (): JournalEntry[] => { try { return JSON.parse(localStorage.getItem(JOURNAL_KEY)||'[]'); } catch { return []; } };
const saveJournals = (j: JournalEntry[]) => { try { localStorage.setItem(JOURNAL_KEY, JSON.stringify(j)); } catch { /* */ } };

const getNowStrings = () => {
  const now = new Date();
  return { date: now.toLocaleDateString('en-IN', { weekday:'long', day:'numeric', month:'long', year:'numeric' }), time: now.toLocaleTimeString('en-IN', { hour:'2-digit', minute:'2-digit', hour12:true }), timestamp: now.getTime() };
};

const getAutoText = (steps: number, hr: number, hour: number) => {
  const t = hour < 12 ? 'Subah' : hour < 17 ? 'Dopahar' : hour < 21 ? 'Shaam' : 'Raat';
  const s = steps>8000 ? `${steps.toLocaleString()} steps — zabardast goal ke karib! 🔥` : steps>5000 ? `${steps.toLocaleString()} steps — achha chal raha hai! 💪` : steps>2000 ? `${steps.toLocaleString()} steps hue hain abhi. Thoda aur! 🚶` : `Sirf ${steps.toLocaleString()} steps — chalo bahar nikalte hain! 👟`;
  const h = hr > 0 ? ` Heart rate ${hr} bpm.` : '';
  return `📍 ${t} update — ${s}${h}`;
};

const useLiveClock = () => {
  const [now, setNow] = useState(new Date());
  useEffect(() => { const id = setInterval(() => setNow(new Date()), 1000); return () => clearInterval(id); }, []);
  return now;
};

const goalLabel: Record<string, string> = { weight_loss: '🔥 Weight Loss', muscle_gain: '💪 Muscle Gain', maintain: '⚖️ Maintain' };
const levelLabel: Record<string, string> = { beginner: '🌱 Beginner', intermediate: '⚡ Intermediate', advanced: '🏆 Advanced' };

const WorkoutCalendar = ({ workouts, onDayClick }: { workouts: WorkoutLog[]; onDayClick: (date: string) => void }) => {
  const [calMonth, setCalMonth] = useState(new Date());
  const year = calMonth.getFullYear();
  const month = calMonth.getMonth();
  const firstDay = new Date(year, month, 1).getDay();
  const daysInMonth = new Date(year, month + 1, 0).getDate();
  const workoutDates = new Set(workouts.map(w => w.date));
  const today = todayStr();
  const monthName = calMonth.toLocaleDateString('en-IN', { month: 'long', year: 'numeric' });
  const days = ['S','M','T','W','T','F','S'];
  const cells: (number | null)[] = [];
  for (let i = 0; i < firstDay; i++) cells.push(null);
  for (let i = 1; i <= daysInMonth; i++) cells.push(i);
  const workoutsThisMonth = workouts.filter(w => { const d = new Date(w.date); return d.getMonth() === month && d.getFullYear() === year; }).length;
  return (
    <div style={{ background:'#111', borderRadius:20, padding:16, border:'1px solid #1a1a1a', marginBottom:14 }}>
      <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:12 }}>
        <motion.button whileTap={{ scale:0.9 }} onClick={() => setCalMonth(new Date(year, month-1, 1))} style={{ background:'#1a1a1a', border:'none', color:'#fff', borderRadius:8, padding:'6px 10px', cursor:'pointer', fontSize:14 }}>‹</motion.button>
        <div style={{ textAlign:'center' }}>
          <div style={{ fontSize:13, fontWeight:800, color:'#E8FF6B' }}>{monthName}</div>
          <div style={{ fontSize:10, color:'#555', marginTop:2 }}>{workoutsThisMonth} workouts 💪</div>
        </div>
        <motion.button whileTap={{ scale:0.9 }} onClick={() => setCalMonth(new Date(year, month+1, 1))} style={{ background:'#1a1a1a', border:'none', color:'#fff', borderRadius:8, padding:'6px 10px', cursor:'pointer', fontSize:14 }}>›</motion.button>
      </div>
      <div style={{ display:'grid', gridTemplateColumns:'repeat(7,1fr)', gap:4, marginBottom:6 }}>
        {days.map((d,i) => (<div key={i} style={{ textAlign:'center', fontSize:9, color:'#444', fontWeight:700, padding:'4px 0' }}>{d}</div>))}
      </div>
      <div style={{ display:'grid', gridTemplateColumns:'repeat(7,1fr)', gap:4 }}>
        {cells.map((day, i) => {
          if (!day) return <div key={i} />;
          const dateStr = `${year}-${String(month+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;
          const hasWorkout = workoutDates.has(dateStr);
          const isToday = dateStr === today;
          return (
            <motion.div key={i} whileTap={{ scale:0.85 }} onClick={() => hasWorkout && onDayClick(dateStr)}
              style={{ aspectRatio:'1', borderRadius:8, display:'flex', alignItems:'center', justifyContent:'center', fontSize:11, fontWeight:hasWorkout||isToday?800:400, cursor:hasWorkout?'pointer':'default', background: hasWorkout ? '#E8FF6B22' : isToday ? '#1a1a2e' : 'transparent', border: isToday ? '1px solid #6B8EFF44' : hasWorkout ? '1px solid #E8FF6B44' : '1px solid transparent', color: hasWorkout ? '#E8FF6B' : isToday ? '#6B8EFF' : '#555', position:'relative' }}>
              {day}
              {hasWorkout && <div style={{ position:'absolute', bottom:2, left:'50%', transform:'translateX(-50%)', width:4, height:4, borderRadius:'50%', background:'#E8FF6B' }} />}
            </motion.div>
          );
        })}
      </div>
      <div style={{ display:'flex', gap:12, marginTop:12, justifyContent:'center' }}>
        <div style={{ display:'flex', alignItems:'center', gap:4, fontSize:9, color:'#555' }}><div style={{ width:8, height:8, borderRadius:2, background:'#E8FF6B44', border:'1px solid #E8FF6B44' }} />Workout day</div>
        <div style={{ display:'flex', alignItems:'center', gap:4, fontSize:9, color:'#555' }}><div style={{ width:8, height:8, borderRadius:2, background:'#1a1a2e', border:'1px solid #6B8EFF44' }} />Today</div>
      </div>
    </div>
  );
};

export default function App() {
  const [currentView, setCurrentView] = useState<ViewType>('login');
  const [user, setUser] = useState<any>(null);
  const [accessToken, setAccessToken] = useState<string>('');
  const [refreshing, setRefreshing] = useState(false);
  const [lastSynced, setLastSynced] = useState<Date | null>(null);
  const [syncError, setSyncError] = useState<string | null>(null);
  const [phoneNumber, setPhoneNumber] = useState('+91');
  const [otp, setOtp] = useState('');
  const [authStage, setAuthStage] = useState<'phone' | 'otp'>('phone');
  const [verificationId, setVerificationId] = useState<string>('');
  const [nextSyncIn, setNextSyncIn] = useState(AUTO_REFRESH_MS / 1000);
  const [notifEnabled, setNotifEnabled] = useState(false);
  const [userProfile, setUserProfile] = useState<UserProfile | null>(null);  const [showProfileSetup, setShowProfileSetup] = useState(false);

  // Workout Planner
  const [showWorkoutPlanner, setShowWorkoutPlanner] = useState(false);
  const [planWorkoutTime, setPlanWorkoutTime] = useState('07:00');
  const [planWorkoutDesc, setPlanWorkoutDesc] = useState('');
  const [savedPlan, setSavedPlan] = useState(loadWorkoutPlan);

  const [weightLog, setWeightLog] = useState<WeightEntry[]>(loadWeights);
  const [weightInput, setWeightInput] = useState('');
  const [weightSaved, setWeightSaved] = useState(false);

  const [workoutLog, setWorkoutLog] = useState<WorkoutLog[]>(loadWorkouts);
  const [voiceText, setVoiceText] = useState('');
  const [isListening, setIsListening] = useState(false);
  const [parsedExercises, setParsedExercises] = useState<WorkoutExercise[]>([]);
  const [workoutAnalysis, setWorkoutAnalysis] = useState('');
  const [showVoiceInput, setShowVoiceInput] = useState(false);
  const [workoutDuration, setWorkoutDuration] = useState('');
  const [workoutNotes, setWorkoutNotes] = useState('');
  const [selectedCalDay, setSelectedCalDay] = useState<string | null>(null);
  const [calView, setCalView] = useState<'log' | 'calendar'>('log');
  const recognitionRef = useRef<any>(null);

  const autoSyncRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const countdownRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const hourlyRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const fitDataRef = useRef<FitDataType | null>(null);
  const lastHourly = useRef<number>(0);
  const liveClock = useLiveClock();

  const [toasts, setToasts] = useState<Toast[]>([]);
  const toastId = useRef(0);
  const showToast = useCallback((message: string, type: Toast['type'] = 'info') => {
    const id = ++toastId.current;
    setToasts(t => [...t, { id, message, type }]);
    setTimeout(() => setToasts(t => t.filter(x => x.id !== id)), 3500);
  }, []);

  const [fitData, setFitData] = useState<FitDataType>({
    steps: { today:0, weeklyData:Array(7).fill(0), goal:10_000 },
    heartRate: { current:0, avg:0, max:0, min:0 },
    sleep: { hours:'0', quality:'No data' },
  });
  const [sleepStages, setSleepStages] = useState<NightSleepData[]>(generateMockSleepData());
  const [selectedNight, setSelectedNight] = useState<NightSleepData | null>(null);
  const [journals, setJournals] = useState<JournalEntry[]>(loadJournals);
  const [journalText, setJournalText] = useState('');
  const [selectedMood, setSelectedMood] = useState('😊');
  const [showJournalForm, setShowJournalForm] = useState(false);
  const [journalFilter, setJournalFilter] = useState<string>('all');

  useEffect(() => { fitDataRef.current = fitData; }, [fitData]);
  useEffect(() => { saveWeights(weightLog); }, [weightLog]);
  useEffect(() => { saveWorkouts(workoutLog); }, [workoutLog]);

  const startListening = () => {
    const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
    if (!SpeechRecognition) { showToast('Voice recognition not supported', 'error'); return; }
    const recognition = new SpeechRecognition();
    recognition.lang = 'hi-IN'; recognition.continuous = false; recognition.interimResults = false;
    recognition.onstart = () => setIsListening(true);
    recognition.onresult = (e: any) => {
      const transcript = e.results[0][0].transcript;
      setVoiceText(transcript);
      const parsed = parseVoiceWorkout(transcript);
      setParsedExercises(parsed); setWorkoutAnalysis(analyzeWorkout(parsed)); playSound('success');
    };
    recognition.onerror = () => { setIsListening(false); showToast('Voice error — dobara try karo', 'error'); };
    recognition.onend = () => setIsListening(false);
    recognitionRef.current = recognition; recognition.start();
  };

  const stopListening = () => { recognitionRef.current?.stop(); setIsListening(false); };

  const handleVoiceProcess = () => {
    if (!voiceText.trim()) return;
    const parsed = parseVoiceWorkout(voiceText);
    setParsedExercises(parsed); setWorkoutAnalysis(analyzeWorkout(parsed));
  };

  const saveWorkout = () => {
    if (!parsedExercises.length && !voiceText.trim()) return;
    const now = new Date();
    const entry: WorkoutLog = { id: Date.now(), date: todayStr(), dateLabel: now.toLocaleDateString('en-IN', { weekday:'long', day:'numeric', month:'long' }), timestamp: Date.now(), exercises: parsedExercises, duration: parseInt(workoutDuration) || 0, notes: workoutNotes, voiceText };
    setWorkoutLog(prev => [entry, ...prev].slice(0, 100));
    setVoiceText(''); setParsedExercises([]); setWorkoutAnalysis(''); setWorkoutDuration(''); setWorkoutNotes(''); setShowVoiceInput(false);
    playSound('success'); showToast('💪 Workout saved!', 'success');
  };

  const deleteWorkout = (id: number) => { setWorkoutLog(prev => prev.filter(w => w.id !== id)); playSound('click'); };

  const handleWeightSave = () => {
    const kg = parseFloat(weightInput);
    if (!kg || kg < 20 || kg > 300) return;
    const today = todayStr();
    setWeightLog(prev => { const filtered = prev.filter(e => e.date !== today); return [...filtered, { date: today, weight: kg }].slice(-30); });
    setWeightInput(''); setWeightSaved(true); playSound('success');
    setTimeout(() => setWeightSaved(false), 2000);
  };

  const graphData = weightLog.slice(-14);
  const wWeights = graphData.map(e => e.weight);
  const minW = wWeights.length ? Math.min(...wWeights) - 2 : 50;
  const maxW = wWeights.length ? Math.max(...wWeights) + 2 : 100;
  const wRange = maxW - minW || 1;
  const latestW = wWeights[wWeights.length - 1] ?? null;
  const firstW = wWeights[0] ?? null;
  const wChange = latestW && firstW ? +(latestW - firstW).toFixed(1) : null;
  const GW = 260; const GH = 80;
  const wPoints = graphData.map((e, i) => { const x = graphData.length < 2 ? GW/2 : (i/(graphData.length-1))*GW; const y = GH - ((e.weight - minW)/wRange)*GH; return `${x.toFixed(1)},${y.toFixed(1)}`; }).join(' ');

  useEffect(() => {
    let phoneCodeSentListener: any;
    let phoneVerificationCompletedListener: any;
    const setupListeners = async () => {
      phoneCodeSentListener = await FirebaseAuthentication.addListener('phoneCodeSent', (event) => {
        setVerificationId(event.verificationId);
      });
      phoneVerificationCompletedListener = await FirebaseAuthentication.addListener('phoneVerificationCompleted', (event) => {
        const firebaseUser = event.user;
        const savedUser = {
          uid: firebaseUser?.uid,
          phoneNumber: firebaseUser?.phoneNumber,
          displayName: firebaseUser?.displayName,
          email: firebaseUser?.email,
        };
        setUser(savedUser);
        localStorage.setItem('userToken', JSON.stringify(savedUser));
        setCurrentView('home');
        setOtp('');
        setAuthStage('phone');
        showToast('Login successful!', 'success');
      });
    };
    setupListeners();
    return () => {
      if (phoneCodeSentListener) phoneCodeSentListener.remove();
      if (phoneVerificationCompletedListener) phoneVerificationCompletedListener.remove();
    };
  }, []);

  useEffect(() => {
    GoogleAuth.initialize({
      clientId: import.meta.env.VITE_GOOGLE_CLIENT_ID,
      scopes: [
        'profile',
        'email',
        'https://www.googleapis.com/auth/fitness.activity.read',
        'https://www.googleapis.com/auth/fitness.body.read',
        'https://www.googleapis.com/auth/fitness.sleep.read',
        'https://www.googleapis.com/auth/fitness.heart_rate.read',
      ],
      grantOfflineAccess: true,
    });
  }, []);

  useEffect(() => {
    const savedToken = localStorage.getItem('fit_token');
    if (savedToken) {
      setAccessToken(savedToken);
      syncFitData(savedToken, true, false);
      startAutoSync(savedToken);
    }
  }, []);

  useEffect(() => {
    const today = new Date().toDateString();
    const notifiedDay = localStorage.getItem('goal_notified_today');
    if (notifiedDay && notifiedDay !== today) {
      localStorage.removeItem('goal_notified_today');
    }
  }, []);

  const addAutoJournalEntry = useCallback((steps: number, hr: number) => {
    const hour = new Date().getHours();
    const { date, time, timestamp } = getNowStrings();
    const entry: JournalEntry = { id: timestamp, date, time, timestamp, text: getAutoText(steps, hr, hour), mood: steps>8000?'🔥':steps>5000?'💪':'😊', steps, heartRate: hr, autoGenerated: true };
    setJournals(prev => { const u=[entry,...prev]; saveJournals(u); return u; });
  }, []);

  const syncFitData = useCallback(async (token: string, silent = false, notify = false) => {
    setRefreshing(true); setSyncError(null);
    if (!silent) playSound('sync');
    try {
      const raw = await fetchGoogleFitData(token);
      const steps = parseSteps(raw.steps);
      const heartRate = parseHeartRate(raw.heartRate);
      const nights = parseSleepStages(raw.sleepStages);
      const sleepSum = deriveSleepSummary(nights);
      setFitData({ steps, heartRate, sleep: sleepSum });
      setSleepStages(nights); setLastSynced(new Date()); setNextSyncIn(AUTO_REFRESH_MS / 1000);
      if (notify) {
        if (steps.today >= steps.goal && !localStorage.getItem('goal_notified_today')) {
          localStorage.setItem('goal_notified_today', new Date().toDateString());
          sendNotification('🎉 Goal Complete!', `${steps.today.toLocaleString()} steps — aaj ka goal poora!`);
        }
        if (heartRate.current > 140) sendNotification('❤️ High HR Alert', `${heartRate.current} bpm — thoda rest lo!`);
      }
      if (!silent) { playSound('success'); showToast(`✅ ${steps.today.toLocaleString()} steps synced`, 'success'); }
    } catch (err: any) {
      const msg = err?.message || 'Sync failed';
      if (msg.includes('401')) {
        // Token expired
        localStorage.removeItem('userToken');
        setUser(null);
        setAccessToken('');
        setCurrentView('login');
        showToast('Session expired, please sign in again', 'error');
      } else {
        setSyncError(msg);
        if (!silent) { playSound('click'); showToast(msg, 'error'); }
      }
    } finally { setRefreshing(false); }
  }, [showToast]);

  const startAutoSync = useCallback((token: string) => {
    if (autoSyncRef.current) clearInterval(autoSyncRef.current);
    if (countdownRef.current) clearInterval(countdownRef.current);
    if (hourlyRef.current) clearInterval(hourlyRef.current);
    autoSyncRef.current = setInterval(() => syncFitData(token, true, true), AUTO_REFRESH_MS);
    countdownRef.current = setInterval(() => setNextSyncIn(prev => prev <= 1 ? AUTO_REFRESH_MS/1000 : prev - 1), 1000);
    hourlyRef.current = setInterval(() => {
      const fd = fitDataRef.current; if (!fd) return;
      const now = Date.now();
      if (now - lastHourly.current < HOURLY_MS - 5000) return;
      lastHourly.current = now;
      addAutoJournalEntry(fd.steps.today, fd.heartRate.avg);
    }, HOURLY_MS);
  }, [syncFitData, addAutoJournalEntry]);

  useEffect(() => () => {
    if (autoSyncRef.current) clearInterval(autoSyncRef.current);
    if (countdownRef.current) clearInterval(countdownRef.current);
    if (hourlyRef.current) clearInterval(hourlyRef.current);
  }, []);

  const sendOtp = async () => {
    try {
      const phone = phoneNumber.trim().startsWith('+') ? phoneNumber.trim() : `+91${phoneNumber.trim()}`;
      if (!/^[+][0-9]{10,15}$/.test(phone)) { showToast('Valid phone number chahiye', 'error'); return; }
      await FirebaseAuthentication.signInWithPhoneNumber({ phoneNumber: phone });
      setAuthStage('otp');
      showToast(`OTP bhej diya ${phone}`, 'success');
    } catch (error: any) {
      showToast(`OTP error: ${error.message}`, 'error');
    }
  };

  const verifyOtp = async () => {
    if (otp.trim().length !== 6) { showToast('6-digit OTP daalo', 'error'); return; }
    try {
      const result = await FirebaseAuthentication.confirmVerificationCode({ verificationId, verificationCode: otp.trim() });
      const firebaseUser = result.user;
      const savedUser = {
        uid: firebaseUser?.uid,
        phoneNumber: firebaseUser?.phoneNumber,
        displayName: firebaseUser?.displayName,
        email: firebaseUser?.email,
      };
      setUser(savedUser);
      localStorage.setItem('userToken', JSON.stringify(savedUser));
      setCurrentView('home');
      setOtp('');
      setAuthStage('phone');
      showToast('Login successful!', 'success');
    } catch (error: any) {
      showToast(`OTP galat hai: ${error.message}`, 'error');
    }
  };

  const handleProfileComplete = (profile: UserProfile) => {
    setUserProfile(profile); setShowProfileSetup(false); setCurrentView('home');
    playSound('success'); showToast(`Welcome, ${profile.name}! 🎉`, 'success');
  };

  const handleRefresh = () => {
    if (accessToken) { syncFitData(accessToken, false, true); startAutoSync(accessToken); }
    else showToast('No access token','error');
  };

  const handleGoogleFitConnect = async () => {
    try {
      const result = await GoogleAuth.signIn();
      const token = result.authentication.accessToken;
      if (token) {
        setAccessToken(token);
        localStorage.setItem('fit_token', token);
        syncFitData(token, false, true);
        startAutoSync(token);
        showToast('Google Fit connected!', 'success');
      }
    } catch (error: any) {
      showToast(`Google Fit error: ${error.message}`, 'error');
    }
  };

  const handleSignOut = async () => {
    [autoSyncRef, countdownRef, hourlyRef].forEach(r => { if (r.current) clearInterval(r.current); });
    try {
      await FirebaseAuthentication.signOut();
    } catch { /* */ }
    setUser(null); setAccessToken('');
    setFitData({ steps:{today:0,weeklyData:Array(7).fill(0),goal:10_000}, heartRate:{current:0,avg:0,max:0,min:0}, sleep:{hours:'0',quality:'No data'} });
    setSleepStages([]); setLastSynced(null); setSyncError(null);
    localStorage.removeItem('userToken');
    setCurrentView('login'); playSound('success');
  };

  const handleNav = (v: ViewType) => { playSound('click'); setCurrentView(v); };

  const handleEnableNotifications = async () => {
    const granted = await requestNotificationPermission();
    setNotifEnabled(granted);
    if (granted) { showToast('🔔 Notifications enabled!','success'); sendNotification('🔔 HardReps','Active!'); }
    else showToast('Notifications blocked','error');
  };

  const handleSaveWorkoutPlan = async () => {
    if (!planWorkoutDesc.trim()) return;
    const plan = { time: planWorkoutTime, workout: planWorkoutDesc.trim() };
    saveWorkoutPlan(plan); setSavedPlan(plan);
    const success = await scheduleWorkoutReminder(planWorkoutTime, planWorkoutDesc.trim());
    if (success) { showToast(`✅ Reminder set! ${planWorkoutTime} pe notification aayegi`, 'success'); playSound('success'); }
    else showToast('⚠️ Notification schedule nahi hui', 'warning');
    setShowWorkoutPlanner(false); setPlanWorkoutDesc('');
  };

  const addJournal = () => {
    if (!journalText.trim()) return;
    const { date, time, timestamp } = getNowStrings();
    const entry: JournalEntry = { id:timestamp, date, time, timestamp, text:journalText.trim(), mood:selectedMood, steps:fitData.steps.today, heartRate:fitData.heartRate.avg };
    const updated = [entry,...journals]; setJournals(updated); saveJournals(updated);
    setJournalText(''); setSelectedMood('😊'); setShowJournalForm(false);
    playSound('success'); showToast('Journal saved!','success');
  };

  const deleteJournal = (id: number) => {
    const updated = journals.filter(j=>j.id!==id); setJournals(updated); saveJournals(updated); playSound('click');
  };

  const stepPct = Math.min(Math.round((fitData.steps.today/fitData.steps.goal)*100),100);
  const maxSteps = Math.max(...fitData.steps.weeklyData,1);
  const boardPos = Math.max(Math.min(Math.round(stepPct),100),1);
  const journalDates = Array.from(new Set(journals.map(j=>j.date)));
  const filteredJournals = journalFilter==='all' ? journals : journals.filter(j=>j.date===journalFilter);
  const autoCount = journals.filter(j=>j.autoGenerated).length;
  const todayWorkout = workoutLog.find(w => w.date === todayStr());
  const selectedDayWorkouts = selectedCalDay ? workoutLog.filter(w => w.date === selectedCalDay) : [];

  const ToastOverlay = () => (
    <div style={{ position:'fixed',top:48,left:'50%',transform:'translateX(-50%)',zIndex:9999,display:'flex',flexDirection:'column',gap:8,maxWidth:360,width:'90%',pointerEvents:'none' }}>
      <AnimatePresence>
        {toasts.map(t=>(
          <motion.div key={t.id} initial={{ opacity:0,y:-20,scale:0.95 }} animate={{ opacity:1,y:0,scale:1 }} exit={{ opacity:0,y:-10,scale:0.9 }}
            style={{ padding:'12px 16px',borderRadius:14,fontSize:13,fontWeight:600,textAlign:'center', background:t.type==='success'?'#166534':t.type==='error'?'#7f1d1d':t.type==='warning'?'#78350f':'#1e293b', color:t.type==='success'?'#86efac':t.type==='error'?'#fca5a5':t.type==='warning'?'#fde68a':'#94a3b8', border:`1px solid ${t.type==='success'?'#22c55e33':t.type==='error'?'#ef444433':t.type==='warning'?'#f59e0b33':'#334155'}` }}>
            {t.message}
          </motion.div>
        ))}
      </AnimatePresence>
    </div>
  );

  if (showProfileSetup) return (<><ToastOverlay /><ProfileSetup onComplete={handleProfileComplete} existingProfile={userProfile} /></>);

  if (currentView==='login'||!user) return (
    <>
      <ToastOverlay/>
      <div style={{ minHeight:'100vh',background:'#0D0D0D',display:'flex',alignItems:'center',justifyContent:'center',padding:24 }}>
        <motion.div initial={{ opacity:0,scale:0.9 }} animate={{ opacity:1,scale:1 }} style={{ textAlign:'center',maxWidth:390,width:'100%' }}>
          <motion.div animate={{ scale:[1,1.06,1] }} transition={{ repeat:Infinity,duration:2.5 }}
            style={{ width:80,height:80,background:'#E8FF6B',borderRadius:24,display:'flex',alignItems:'center',justifyContent:'center',margin:'0 auto 20px',fontSize:40,boxShadow:'0 0 40px #E8FF6B44' }}>⚡</motion.div>
          <div style={{ fontSize:32,fontWeight:900,color:'#fff',letterSpacing:-1 }}>HardReps</div>
          <div style={{ fontSize:13,color:'#444',marginBottom:16,marginTop:4 }}>Phone OTP Login · HardReps</div>
          <div style={{ background:'#111',borderRadius:20,padding:'18px 24px',marginBottom:24,border:'1px solid #1a1a1a' }}>
            {authStage === 'phone' ? (
              <>
                <div style={{ fontSize:14,color:'#aaa',marginBottom:8,textAlign:'left' }}>Mobile number</div>
                <input
                  value={phoneNumber}
                  onChange={e => setPhoneNumber(e.target.value)}
                  placeholder="+91 98765 43210"
                  style={{ width:'100%',borderRadius:16,border:'1px solid #2a2a2a',background:'#0d0d0d',color:'#fff',padding:'14px 16px',fontSize:14,marginBottom:16,outline:'none' }}
                />
                <motion.button onClick={sendOtp} whileTap={{ scale:0.97 }}
                  style={{ width:'100%',background:'#E8FF6B',color:'#1A1A00',border:'none',fontSize:16,fontWeight:800,padding:'18px 24px',borderRadius:20,cursor:'pointer',marginBottom:12,boxShadow:'0 8px 24px #E8FF6B33' }}>
                  Send OTP
                </motion.button>
              </>
            ) : (
              <>
                <div style={{ fontSize:14,color:'#aaa',marginBottom:8,textAlign:'left' }}>Enter OTP</div>
                <input
                  value={otp}
                  onChange={e => setOtp(e.target.value.replace(/\D/g, ''))}
                  placeholder="6-digit OTP"
                  maxLength={6}
                  style={{ width:'100%',borderRadius:16,border:'1px solid #2a2a2a',background:'#0d0d0d',color:'#fff',padding:'14px 16px',fontSize:14,marginBottom:16,outline:'none' }}
                />
                <motion.button onClick={verifyOtp} whileTap={{ scale:0.97 }}
                  style={{ width:'100%',background:'#E8FF6B',color:'#1A1A00',border:'none',fontSize:16,fontWeight:800,padding:'18px 24px',borderRadius:20,cursor:'pointer',marginBottom:12,boxShadow:'0 8px 24px #E8FF6B33' }}>
                  Verify OTP
                </motion.button>
                <motion.button onClick={() => { setAuthStage('phone'); setOtp(''); }} whileTap={{ scale:0.97 }}
                  style={{ width:'100%',background:'#1a1a1a',color:'#aaa',border:'1px solid #2a2a2a',fontSize:14,fontWeight:700,padding:'14px 20px',borderRadius:20,cursor:'pointer' }}>
                  Change Number
                </motion.button>
              </>
            )}
          </div>
        </motion.div>
      </div>
    </>
  );

  return (
    <>
      <ToastOverlay/>
      <div style={{ minHeight:'100vh',background:'#0D0D0D',color:'#fff',maxWidth:390,margin:'0 auto' }}>

        {/* HOME */}
        {currentView==='home'&&(
          <motion.div initial={{ opacity:0,y:20 }} animate={{ opacity:1,y:0 }} style={{ padding:'48px 20px 120px' }}>
            <div style={{ display:'flex',justifyContent:'space-between',alignItems:'flex-start',marginBottom:8 }}>
              <div>
                <div style={{ fontSize:12,color:'#444' }}>{liveClock.toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'short'})}</div>
                <div style={{ fontSize:22,fontWeight:800,marginTop:2 }}>Hey, {userProfile?.name?.split(' ')[0] || 'User'} 👋</div>
                {userProfile && <div style={{ fontSize:11,color:'#444',marginTop:2 }}>{goalLabel[userProfile.fitnessGoal] || ''} · {levelLabel[userProfile.fitnessLevel] || ''}</div>}
              </div>
              <div style={{ display:'flex',alignItems:'center',gap:8 }}>
                <div style={{ textAlign:'right' }}>
                  <div style={{ fontSize:20,fontWeight:900,color:'#E8FF6B' }}>{liveClock.toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',hour12:true})}</div>
                  <div style={{ fontSize:10,color:'#333' }}>:{liveClock.getSeconds().toString().padStart(2,'0')}</div>
                </div>
                <motion.button onClick={handleRefresh} animate={{ rotate:refreshing?360:0 }} transition={{ repeat:refreshing?Infinity:0,duration:0.8,ease:'linear' }}
                  style={{ background:'none',border:'none',cursor:'pointer',padding:6 }}>
                  <svg width="20" height="20" fill="none" stroke={refreshing?'#E8FF6B':'#444'} strokeWidth="2" viewBox="0 0 24 24">
                    <polyline points="23 4 23 10 17 10"/><path d="M20.49 15a9 9 0 1 1-2.12-9.36L23 10"/>
                  </svg>
                </motion.button>
              </div>
            </div>

            <motion.div animate={{ borderColor:refreshing?'#E8FF6B33':'#1a1a1a' }}
              style={{ background:'#111',borderRadius:14,padding:'10px 14px',marginBottom:12,border:'1px solid #1a1a1a',display:'flex',justifyContent:'space-between',alignItems:'center' }}>
              <div style={{ fontSize:11,color:syncError?'#FF6B6B':lastSynced?'#22c55e':'#444' }}>
                {refreshing?'🔄 Syncing…':syncError?`⚠️ ${syncError}`:lastSynced?`✅ ${lastSynced.toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',hour12:true})} pe synced`:'⏳ Sync hona baaki'}
              </div>
              {lastSynced&&!refreshing&&<div style={{ fontSize:10,color:'#333',background:'#0a0a0a',padding:'3px 8px',borderRadius:8 }}>next {nextSyncIn}s</div>}
            </motion.div>

            {!accessToken && (
              <button
                onClick={handleGoogleFitConnect}
                style={{
                  background: '#4CAF50',
                  color: '#fff',
                  border: 'none',
                  padding: '8px 16px',
                  borderRadius: 12,
                  fontSize: 12,
                  fontWeight: 700,
                  cursor: 'pointer',
                  marginBottom: 12,
                }}
              >
                Connect Google Fit
              </button>
            )}

            <motion.div initial={{ opacity:0,y:10 }} animate={{ opacity:1,y:0 }} transition={{ delay:0.1 }}
              style={{ background:'#1A1A1A',borderRadius:24,padding:20,border:'1px solid #222',marginBottom:14 }}>
              <div style={{ display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:16 }}>
                <div style={{ fontSize:10,color:'#444',letterSpacing:2,textTransform:'uppercase' }}>Google Fit · Live</div>
                <motion.div animate={{ opacity:[1,0.3,1] }} transition={{ repeat:Infinity,duration:1.8 }} style={{ width:6,height:6,borderRadius:'50%',background:'#22c55e' }}/>
              </div>
              <div style={{ display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:12 }}>
                {[
                  [fitData.steps.today.toLocaleString(),'Steps',`${stepPct}% goal`,'#E8FF6B'],
                  [String(fitData.heartRate.avg||'—'),'BPM',`${fitData.heartRate.min}–${fitData.heartRate.max}`,'#FF6B6B'],
                  [`${fitData.sleep.hours}h`,'Sleep',fitData.sleep.quality,'#6B8EFF'],
                ].map(([val,label,sub,color],i)=>(
                  <div key={i}>
                    <div style={{ fontSize:26,fontWeight:900,color,letterSpacing:-1 }}>{val}</div>
                    <div style={{ fontSize:10,color:'#555',marginTop:3 }}>{label}</div>
                    <div style={{ fontSize:9,color:'#333',marginTop:1 }}>{sub}</div>
                  </div>
                ))}
              </div>
            </motion.div>

            <motion.div initial={{ opacity:0,y:10 }} animate={{ opacity:1,y:0 }} transition={{ delay:0.15 }}
              whileTap={{ scale:0.98 }} onClick={()=>handleNav('train')}
              style={{ background: todayWorkout ? '#1a2a0a' : '#111', borderRadius:20, padding:16, border:`1px solid ${todayWorkout?'#E8FF6B33':'#1a1a1a'}`, marginBottom:14, cursor:'pointer' }}>
              <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center' }}>
                <div>
                  <div style={{ fontSize:11, color: todayWorkout?'#E8FF6B':'#444', letterSpacing:1, textTransform:'uppercase', marginBottom:4 }}>
                    {todayWorkout ? '✅ Aaj Ka Workout' : '🎤 Voice Workout Log'}
                  </div>
                  {todayWorkout ? (
                    <div>
                      <div style={{ fontSize:16, fontWeight:800, color:'#fff' }}>{todayWorkout.exercises.length} exercises</div>
                      <div style={{ fontSize:11, color:'#555', marginTop:2 }}>{todayWorkout.exercises.map(e=>e.name).join(', ').slice(0,40)}...</div>
                    </div>
                  ) : (
                    <div style={{ fontSize:14, color:'#555' }}>Bolke apna workout log karo!</div>
                  )}
                </div>
                <div style={{ fontSize:28 }}>{todayWorkout ? '💪' : '🎙️'}</div>
              </div>
            </motion.div>

            <motion.div initial={{ opacity:0,y:10 }} animate={{ opacity:1,y:0 }} transition={{ delay:0.2 }}
              whileTap={{ scale:1.01 }} onClick={()=>handleNav('stats')}
              style={{ background:'#E8FF6B',borderRadius:24,padding:20,cursor:'pointer',marginBottom:14 }}>
              <div style={{ display:'flex',justifyContent:'space-between',marginBottom:14 }}>
                <div>
                  <div style={{ fontSize:10,color:'#5A6000',letterSpacing:2,textTransform:'uppercase' }}>Steps · 7 Din</div>
                  <div style={{ fontSize:24,fontWeight:900,color:'#1A1A00',marginTop:2 }}>{fitData.steps.today.toLocaleString()}</div>
                </div>
                <div style={{ textAlign:'right' }}>
                  <div style={{ fontSize:9,color:'#5A6000' }}>Weekly avg</div>
                  <div style={{ fontSize:16,fontWeight:800,color:'#1A1A00' }}>{Math.round(fitData.steps.weeklyData.reduce((a,b)=>a+b,0)/7).toLocaleString()}</div>
                </div>
              </div>
              <div style={{ display:'flex',alignItems:'flex-end',gap:5,height:70,marginBottom:10 }}>
                {fitData.steps.weeklyData.map((s,i)=>{
                  const pct=(s/maxSteps)*100; const isToday=i===fitData.steps.weeklyData.length-1;
                  return (
                    <motion.div key={i} style={{ flex:1,display:'flex',flexDirection:'column',justifyContent:'flex-end' }} initial={{ scaleY:0 }} animate={{ scaleY:1 }} transition={{ delay:i*0.06,duration:0.5 }}>
                      <div style={{ background:isToday?'#1A1A00':'#B8CC00',borderRadius:'5px 5px 0 0',height:`${Math.max(pct,4)}%`,opacity:isToday?1:0.55 }}/>
                    </motion.div>
                  );
                })}
              </div>
              <div style={{ display:'flex' }}>
                {['M','T','W','T','F','S','S'].map((d,i)=>(
                  <span key={i} style={{ flex:1,textAlign:'center',fontSize:9,color:i===6?'#1A1A00':'#8A9A00',fontWeight:i===6?800:400 }}>{d}</span>
                ))}
              </div>
            </motion.div>

            <div style={{ display:'flex',gap:8 }}>
              <motion.button onClick={handleEnableNotifications} whileTap={{ scale:0.97 }}
                style={{ flex:1,background:'#111',color:notifEnabled?'#22c55e':'#555',border:`1px solid ${notifEnabled?'#22c55e33':'#222'}`,fontSize:12,fontWeight:600,padding:14,borderRadius:16,cursor:'pointer' }}>
                {notifEnabled?'🔔 Notifs ON':'🔕 Enable Notifs'}
              </motion.button>
              <motion.button onClick={handleSignOut} whileTap={{ scale:0.97 }}
                style={{ flex:1,background:'#111',color:'#FF6B6B',border:'1px solid #FF6B6B22',fontSize:12,fontWeight:600,padding:14,borderRadius:16,cursor:'pointer' }}>
                🔓 Sign Out
              </motion.button>
            </div>

            {/* Workout Planner */}
            <motion.div initial={{ opacity:0,y:10 }} animate={{ opacity:1,y:0 }} transition={{ delay:0.3 }} style={{ marginTop:10 }}>
              <motion.button onClick={()=>{ setShowWorkoutPlanner(v=>!v); playSound('click'); }} whileTap={{ scale:0.97 }}
                style={{ width:'100%',background:'#111',color:'#E8FF6B',border:'1px solid #E8FF6B33',fontSize:13,fontWeight:700,padding:14,borderRadius:16,cursor:'pointer' }}>
                {savedPlan ? `⏰ ${savedPlan.time} — ${savedPlan.workout.slice(0,25)}` : '📅 Kal Ka Workout Plan Karo'}
              </motion.button>
              <AnimatePresence>
                {showWorkoutPlanner && (
                  <motion.div initial={{ opacity:0,height:0 }} animate={{ opacity:1,height:'auto' }} exit={{ opacity:0,height:0 }}
                    style={{ overflow:'hidden',background:'#111',borderRadius:16,padding:16,marginTop:8,border:'1px solid #E8FF6B22' }}>
                    <div style={{ fontSize:12,color:'#E8FF6B',fontWeight:700,marginBottom:12 }}>📅 Kal Ka Workout Plan</div>
                    <div style={{ fontSize:11,color:'#555',marginBottom:6 }}>Kitne baje workout karoge?</div>
                    <input type="time" value={planWorkoutTime} onChange={e=>setPlanWorkoutTime(e.target.value)}
                      style={{ width:'100%',background:'#1a1a1a',border:'1px solid #2a2a2a',borderRadius:10,padding:'10px 14px',color:'#fff',fontSize:14,outline:'none',marginBottom:12,boxSizing:'border-box' }}/>
                    <div style={{ fontSize:11,color:'#555',marginBottom:6 }}>Kya workout karoge?</div>
                    <input value={planWorkoutDesc} onChange={e=>setPlanWorkoutDesc(e.target.value)}
                      placeholder="e.g. Chest day, bench press..."
                      style={{ width:'100%',background:'#1a1a1a',border:'1px solid #2a2a2a',borderRadius:10,padding:'10px 14px',color:'#fff',fontSize:13,outline:'none',marginBottom:12,boxSizing:'border-box' }}/>
                    <div style={{ display:'flex',gap:8 }}>
                      <motion.button whileTap={{ scale:0.95 }} onClick={()=>setShowWorkoutPlanner(false)}
                        style={{ flex:1,background:'#1a1a1a',color:'#555',border:'1px solid #222',borderRadius:10,padding:'10px 0',fontSize:12,fontWeight:600,cursor:'pointer' }}>
                        Cancel
                      </motion.button>
                      <motion.button whileTap={{ scale:0.95 }} onClick={handleSaveWorkoutPlan} disabled={!planWorkoutDesc.trim()}
                        style={{ flex:2,background:'#E8FF6B',color:'#1a1a00',border:'none',borderRadius:10,padding:'10px 0',fontSize:13,fontWeight:800,cursor:'pointer',opacity:planWorkoutDesc.trim()?1:0.5 }}>
                        💾 Save & Set Reminder
                      </motion.button>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </motion.div>
          </motion.div>
        )}

        {/* TRAIN */}
        {currentView==='train'&&(
          <motion.div initial={{ opacity:0,y:20 }} animate={{ opacity:1,y:0 }} style={{ padding:'48px 20px 120px' }}>
            <div style={{ fontSize:22,fontWeight:900,marginBottom:4 }}>Workout Logger</div>
            <div style={{ fontSize:12,color:'#444',marginBottom:16 }}>Voice se log karo · Calendar dekho</div>
            <div style={{ display:'flex',gap:6,marginBottom:16,background:'#111',borderRadius:14,padding:4,border:'1px solid #1a1a1a' }}>
              {[['log','📝 Log'],['calendar','📅 Calendar']].map(([v,l])=>(
                <motion.button key={v} whileTap={{ scale:0.95 }} onClick={()=>{ setCalView(v as any); playSound('click'); }}
                  style={{ flex:1,background:calView===v?'#E8FF6B':'transparent',color:calView===v?'#1a1a00':'#555',border:'none',borderRadius:10,padding:'10px 0',fontSize:12,fontWeight:700,cursor:'pointer' }}>
                  {l}
                </motion.button>
              ))}
            </div>

            {calView === 'log' && (
              <>
                <motion.div initial={{ opacity:0,y:10 }} animate={{ opacity:1,y:0 }}
                  style={{ background:'#111',borderRadius:20,padding:16,border:'1px solid #1a1a1a',marginBottom:14 }}>
                  <div style={{ display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:12 }}>
                    <div style={{ fontSize:12,color:'#555',letterSpacing:1,textTransform:'uppercase' }}>🎤 Voice Workout</div>
                    <motion.button whileTap={{ scale:0.95 }} onClick={()=>{ setShowVoiceInput(v=>!v); playSound('click'); }}
                      style={{ background:'#E8FF6B',color:'#1a1a00',border:'none',borderRadius:10,padding:'6px 12px',fontSize:11,fontWeight:700,cursor:'pointer' }}>
                      {showVoiceInput ? '✕ Close' : '+ New'}
                    </motion.button>
                  </div>
                  <AnimatePresence>
                    {showVoiceInput && (
                      <motion.div initial={{ opacity:0,height:0 }} animate={{ opacity:1,height:'auto' }} exit={{ opacity:0,height:0 }} style={{ overflow:'hidden' }}>
                        <div style={{ display:'flex',justifyContent:'center',marginBottom:16 }}>
                          <motion.button whileTap={{ scale:0.9 }}
                            animate={isListening ? { scale:[1,1.1,1], boxShadow:['0 0 0px #FF6B6B', '0 0 30px #FF6B6B', '0 0 0px #FF6B6B'] } : {}}
                            transition={{ repeat:isListening?Infinity:0, duration:1 }}
                            onClick={isListening ? stopListening : startListening}
                            style={{ width:80,height:80,borderRadius:'50%',background:isListening?'#FF6B6B':'#E8FF6B',border:'none',fontSize:32,cursor:'pointer',display:'flex',alignItems:'center',justifyContent:'center',boxShadow:isListening?'0 0 20px #FF6B6B55':'0 0 20px #E8FF6B33' }}>
                            {isListening ? '⏹' : '🎙️'}
                          </motion.button>
                        </div>
                        <div style={{ textAlign:'center',fontSize:11,color:isListening?'#FF6B6B':'#555',marginBottom:12 }}>
                          {isListening ? '🔴 Sun raha hoon... bolte raho!' : 'Mic dabaao aur workout bolo'}
                        </div>
                        <textarea value={voiceText} onChange={e => setVoiceText(e.target.value)}
                          placeholder="Ya yahan type karo: '3 sets bench press 80kg, 20 push ups'"
                          style={{ width:'100%',background:'#1a1a1a',border:'1px solid #2a2a2a',borderRadius:12,padding:'10px 14px',color:'#fff',fontSize:13,outline:'none',minHeight:80,resize:'vertical',boxSizing:'border-box',fontFamily:'inherit',lineHeight:1.6 }}/>
                        <div style={{ display:'flex',gap:8,marginTop:8,marginBottom:12 }}>
                          <input value={workoutDuration} onChange={e=>setWorkoutDuration(e.target.value)} placeholder="Duration (min)" type="number"
                            style={{ flex:1,background:'#1a1a1a',border:'1px solid #2a2a2a',borderRadius:10,padding:'8px 12px',color:'#fff',fontSize:13,outline:'none' }}/>
                          <input value={workoutNotes} onChange={e=>setWorkoutNotes(e.target.value)} placeholder="Notes (optional)"
                            style={{ flex:2,background:'#1a1a1a',border:'1px solid #2a2a2a',borderRadius:10,padding:'8px 12px',color:'#fff',fontSize:13,outline:'none' }}/>
                        </div>
                        <motion.button whileTap={{ scale:0.95 }} onClick={handleVoiceProcess}
                          style={{ width:'100%',background:'#1a1a2e',color:'#6B8EFF',border:'1px solid #6B8EFF33',borderRadius:12,padding:'10px 0',fontSize:13,fontWeight:700,cursor:'pointer',marginBottom:8 }}>
                          🔍 Analyze Workout
                        </motion.button>
                        {workoutAnalysis && (
                          <motion.div initial={{ opacity:0,y:10 }} animate={{ opacity:1,y:0 }}
                            style={{ background:'#0a1a0a',borderRadius:12,padding:12,marginBottom:10,border:'1px solid #22c55e22' }}>
                            <div style={{ fontSize:11,color:'#22c55e',whiteSpace:'pre-line',lineHeight:1.8 }}>{workoutAnalysis}</div>
                          </motion.div>
                        )}
                        {parsedExercises.length > 0 && (
                          <div style={{ marginBottom:10 }}>
                            <div style={{ fontSize:10,color:'#555',letterSpacing:1,textTransform:'uppercase',marginBottom:8 }}>Detected Exercises</div>
                            {parsedExercises.map((ex,i) => (
                              <div key={i} style={{ background:'#1a1a1a',borderRadius:10,padding:'10px 12px',marginBottom:6,display:'flex',justifyContent:'space-between',alignItems:'center' }}>
                                <div>
                                  <div style={{ fontSize:13,fontWeight:700,color:'#fff' }}>{ex.name}</div>
                                  <div style={{ fontSize:10,color:'#555',marginTop:2 }}>{ex.muscle}</div>
                                </div>
                                <div style={{ textAlign:'right' }}>
                                  <div style={{ fontSize:13,fontWeight:800,color:'#E8FF6B' }}>{ex.sets}×{ex.reps}</div>
                                  {ex.weight > 0 && <div style={{ fontSize:10,color:'#555' }}>{ex.weight}kg</div>}
                                </div>
                              </div>
                            ))}
                          </div>
                        )}
                        <motion.button whileTap={{ scale:0.95 }} onClick={saveWorkout} disabled={!voiceText.trim()}
                          style={{ width:'100%',background:'#E8FF6B',color:'#1a1a00',border:'none',borderRadius:12,padding:'12px 0',fontSize:14,fontWeight:800,cursor:'pointer',opacity:voiceText.trim()?1:0.5 }}>
                          💾 Save Workout
                        </motion.button>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </motion.div>

                {todayWorkout && (
                  <motion.div initial={{ opacity:0,y:10 }} animate={{ opacity:1,y:0 }}
                    style={{ background:'#0a2a0a',borderRadius:18,padding:14,border:'1px solid #22c55e33',marginBottom:14 }}>
                    <div style={{ fontSize:11,color:'#22c55e',letterSpacing:1,textTransform:'uppercase',marginBottom:10 }}>✅ Aaj Ka Workout</div>
                    {todayWorkout.exercises.map((ex,i) => (
                      <div key={i} style={{ display:'flex',justifyContent:'space-between',padding:'6px 0',borderBottom:i<todayWorkout.exercises.length-1?'1px solid #1a2a1a':'none' }}>
                        <div>
                          <div style={{ fontSize:13,fontWeight:600 }}>{ex.name}</div>
                          <div style={{ fontSize:10,color:'#555' }}>{ex.muscle}</div>
                        </div>
                        <div style={{ textAlign:'right' }}>
                          <div style={{ fontSize:12,fontWeight:800,color:'#E8FF6B' }}>{ex.sets}×{ex.reps}</div>
                          {ex.weight > 0 && <div style={{ fontSize:10,color:'#555' }}>{ex.weight}kg</div>}
                        </div>
                      </div>
                    ))}
                  </motion.div>
                )}

                <div style={{ fontSize:11,color:'#444',letterSpacing:1,textTransform:'uppercase',marginBottom:10 }}>Recent Workouts ({workoutLog.length})</div>
                {workoutLog.slice(0,5).map((w,i) => (
                  <motion.div key={w.id} initial={{ opacity:0,y:10 }} animate={{ opacity:1,y:0 }} transition={{ delay:i*0.05 }}
                    style={{ background:'#111',borderRadius:14,padding:'12px 14px',marginBottom:8,border:'1px solid #1a1a1a' }}>
                    <div style={{ display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:8 }}>
                      <div>
                        <div style={{ fontSize:12,fontWeight:700,color:'#E8FF6B' }}>{w.dateLabel}</div>
                        <div style={{ fontSize:10,color:'#555',marginTop:2 }}>{w.exercises.length} exercises{w.duration>0?` · ${w.duration} min`:''}</div>
                      </div>
                      <motion.button whileTap={{ scale:0.9 }} onClick={()=>deleteWorkout(w.id)}
                        style={{ background:'transparent',color:'#333',border:'1px solid #222',padding:'3px 8px',borderRadius:8,fontSize:10,cursor:'pointer' }}>🗑️</motion.button>
                    </div>
                    <div style={{ display:'flex',gap:6,flexWrap:'wrap' }}>
                      {[...new Set(w.exercises.map(e=>e.muscle))].map(m => (
                        <div key={m} style={{ background:'#1a1a1a',borderRadius:6,padding:'3px 8px',fontSize:10,color:'#E8FF6B' }}>{m}</div>
                      ))}
                    </div>
                  </motion.div>
                ))}
                {workoutLog.length === 0 && (
                  <div style={{ textAlign:'center',padding:'30px 0',color:'#333' }}>
                    <div style={{ fontSize:40,marginBottom:10 }}>🎙️</div>
                    <div style={{ fontSize:14,color:'#555' }}>Koi workout nahi yet</div>
                  </div>
                )}
              </>
            )}

            {calView === 'calendar' && (
              <>
                <WorkoutCalendar workouts={workoutLog} onDayClick={(date) => { setSelectedCalDay(date); playSound('click'); }} />
                {(() => {
                  let streak = 0; const d = new Date();
                  while (true) { const ds = d.toISOString().slice(0,10); if (workoutLog.some(w => w.date === ds)) { streak++; d.setDate(d.getDate()-1); } else break; }
                  return streak > 0 ? (
                    <div style={{ background:'linear-gradient(135deg,#2a1a00,#1a0a00)',borderRadius:16,padding:16,border:'1px solid #f59e0b33',marginBottom:14,textAlign:'center' }}>
                      <div style={{ fontSize:32 }}>🔥</div>
                      <div style={{ fontSize:28,fontWeight:900,color:'#f59e0b' }}>{streak} day streak!</div>
                      <div style={{ fontSize:11,color:'#555',marginTop:4 }}>Lagatar workout — zabardast! 💪</div>
                    </div>
                  ) : null;
                })()}
                {(() => {
                  const now = new Date();
                  const thisMonth = workoutLog.filter(w => { const d = new Date(w.date); return d.getMonth() === now.getMonth() && d.getFullYear() === now.getFullYear(); });
                  const muscles = thisMonth.flatMap(w => w.exercises.map(e => e.muscle));
                  const muscleCounts: Record<string,number> = {};
                  muscles.forEach(m => muscleCounts[m] = (muscleCounts[m]||0) + 1);
                  const topMuscle = Object.entries(muscleCounts).sort((a,b)=>b[1]-a[1])[0];
                  return (
                    <div style={{ background:'#111',borderRadius:16,padding:16,border:'1px solid #1a1a1a',marginBottom:14 }}>
                      <div style={{ fontSize:11,color:'#555',letterSpacing:1,textTransform:'uppercase',marginBottom:12 }}>Is Mahine Ka Summary</div>
                      <div style={{ display:'grid',gridTemplateColumns:'1fr 1fr',gap:10 }}>
                        {[['💪',thisMonth.length,'Workouts'],['🎯',thisMonth.reduce((a,w)=>a+w.exercises.length,0),'Total Exercises'],['⏱️',thisMonth.reduce((a,w)=>a+w.duration,0),'Minutes'],['🏆',topMuscle?topMuscle[0]:'—','Top Muscle']].map(([ic,val,label],i)=>(
                          <div key={i} style={{ background:'#1a1a1a',borderRadius:12,padding:'12px 14px' }}>
                            <div style={{ fontSize:18 }}>{ic}</div>
                            <div style={{ fontSize:20,fontWeight:900,color:'#E8FF6B',marginTop:4 }}>{val}</div>
                            <div style={{ fontSize:10,color:'#555',marginTop:2 }}>{label}</div>
                          </div>
                        ))}
                      </div>
                    </div>
                  );
                })()}
                {selectedCalDay && selectedDayWorkouts.length > 0 && (
                  <motion.div initial={{ opacity:0,y:10 }} animate={{ opacity:1,y:0 }}
                    style={{ background:'#0a1a2a',borderRadius:16,padding:16,border:'1px solid #6B8EFF33' }}>
                    <div style={{ display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:12 }}>
                      <div style={{ fontSize:12,color:'#6B8EFF',fontWeight:700 }}>{new Date(selectedCalDay).toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long'})}</div>
                      <motion.button whileTap={{ scale:0.9 }} onClick={()=>setSelectedCalDay(null)} style={{ background:'transparent',border:'none',color:'#555',cursor:'pointer',fontSize:16 }}>✕</motion.button>
                    </div>
                    {selectedDayWorkouts[0].exercises.map((ex,i) => (
                      <div key={i} style={{ display:'flex',justifyContent:'space-between',padding:'6px 0',borderBottom:i<selectedDayWorkouts[0].exercises.length-1?'1px solid #1a1a2a':'none' }}>
                        <div>
                          <div style={{ fontSize:13,fontWeight:600 }}>{ex.name}</div>
                          <div style={{ fontSize:10,color:'#555' }}>{ex.muscle}</div>
                        </div>
                        <div style={{ fontSize:12,fontWeight:800,color:'#E8FF6B' }}>{ex.sets}×{ex.reps}{ex.weight>0?` · ${ex.weight}kg`:''}</div>
                      </div>
                    ))}
                  </motion.div>
                )}
              </>
            )}
          </motion.div>
        )}

        {/* STATS */}
        {currentView==='stats'&&(
          <motion.div initial={{ opacity:0,y:20 }} animate={{ opacity:1,y:0 }} style={{ padding:'48px 20px 120px' }}>
            <div style={{ fontSize:22,fontWeight:900,marginBottom:2 }}>Weekly Stats</div>
            <div style={{ fontSize:11,color:'#444',marginBottom:4 }}>{liveClock.toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</div>
            <div style={{ fontSize:10,color:'#333',marginBottom:16 }}>🔄 Next sync: {nextSyncIn}s</div>
            <div style={{ display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,marginBottom:14 }}>
              {[['Total Steps',fitData.steps.weeklyData.reduce((a,b)=>a+b,0).toLocaleString(),'#E8FF6B','🦶'],['Avg Sleep',`${fitData.sleep.hours}h`,'#6B8EFF','😴'],['Avg HR',String(fitData.heartRate.avg||'—'),'#FF6B6B','❤️'],['Max HR',String(fitData.heartRate.max||'—'),'#FBBC04','🔥']].map(([label,val,color,ic],i)=>(
                <motion.div key={i} initial={{ opacity:0,y:10 }} animate={{ opacity:1,y:0 }} transition={{ delay:i*0.06 }}
                  style={{ background:'#111',borderRadius:18,padding:16,border:'1px solid #1a1a1a' }}>
                  <div style={{ fontSize:22,marginBottom:6 }}>{ic}</div>
                  <div style={{ fontSize:22,fontWeight:900,color:color as string }}>{val}</div>
                  <div style={{ fontSize:11,color:'#444',marginTop:4 }}>{label}</div>
                </motion.div>
              ))}
            </div>
            <motion.div initial={{ opacity:0,y:10 }} animate={{ opacity:1,y:0 }} transition={{ delay:0.15 }}
              style={{ background:'#111',borderRadius:18,padding:16,border:'1px solid #1a1a1a',marginBottom:14 }}>
              <div style={{ display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:12 }}>
                <div style={{ fontSize:11,color:'#555',letterSpacing:1,textTransform:'uppercase' }}>⚖️ Weight Progress</div>
                {wChange !== null && (
                  <div style={{ fontSize:12,fontWeight:700,color:wChange<=0?'#6BFF9E':'#FF6B6B',background:wChange<=0?'#0a2e1a':'#2e0a0a',borderRadius:8,padding:'2px 8px' }}>
                    {wChange>0?'+':''}{wChange} kg
                  </div>
                )}
              </div>
              {graphData.length >= 2 ? (
                <div style={{ position:'relative',marginBottom:10 }}>
                  <div style={{ position:'absolute',left:0,top:0,bottom:16,display:'flex',flexDirection:'column',justifyContent:'space-between' }}>
                    <div style={{ fontSize:9,color:'#444' }}>{maxW.toFixed(0)}</div>
                    <div style={{ fontSize:9,color:'#444' }}>{((maxW+minW)/2).toFixed(0)}</div>
                    <div style={{ fontSize:9,color:'#444' }}>{minW.toFixed(0)}</div>
                  </div>
                  <div style={{ marginLeft:24 }}>
                    <svg width="100%" viewBox={`0 0 ${GW} ${GH}`} style={{ overflow:'visible' }}>
                      <defs><linearGradient id="wg" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#A78BFA" stopOpacity="0.3"/><stop offset="100%" stopColor="#A78BFA" stopOpacity="0"/></linearGradient></defs>
                      {[0,0.5,1].map(t=>(<line key={t} x1="0" y1={GH*(1-t)} x2={GW} y2={GH*(1-t)} stroke="#1a1a1a" strokeWidth="1"/>))}
                      <polyline points={`0,${GH} `+wPoints+` ${GW},${GH}`} fill="url(#wg)" stroke="none"/>
                      <polyline points={wPoints} fill="none" stroke="#A78BFA" strokeWidth="2.5" strokeLinejoin="round" strokeLinecap="round"/>
                      {graphData.map((e,i)=>{ const x=(i/(graphData.length-1))*GW; const y=GH-((e.weight-minW)/wRange)*GH; return <circle key={i} cx={x} cy={y} r="4" fill={i===graphData.length-1?'#A78BFA':'#111'} stroke="#A78BFA" strokeWidth="2"/>; })}
                    </svg>
                    <div style={{ display:'flex',justifyContent:'space-between',marginTop:4 }}>
                      <div style={{ fontSize:9,color:'#444' }}>{graphData[0]?.date.slice(5)}</div>
                      <div style={{ fontSize:9,color:'#A78BFA' }}>{graphData[graphData.length-1]?.date.slice(5)}</div>
                    </div>
                  </div>
                </div>
              ) : (
                <div style={{ textAlign:'center',padding:'20px 0',color:'#333',fontSize:12 }}>{graphData.length===0?'Pehla weight add karo! 👇':'Graph ke liye 2+ entries chahiye'}</div>
              )}
              {latestW && (<div style={{ display:'flex',justifyContent:'center',marginBottom:12 }}><div style={{ fontSize:28,fontWeight:900,color:'#A78BFA' }}>{latestW}<span style={{ fontSize:14,color:'#555',fontWeight:400 }}> kg</span></div></div>)}
              <div style={{ display:'flex',gap:8,alignItems:'center' }}>
                <input type="number" value={weightInput} onChange={e=>setWeightInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&handleWeightSave()} placeholder="Aaj ka weight (kg)" step="0.1" min="20" max="300"
                  style={{ flex:1,background:'#1a1a1a',border:'1px solid #2a2a2a',borderRadius:12,padding:'10px 14px',color:'#fff',fontSize:14,outline:'none' }}/>
                <motion.button whileTap={{ scale:0.92 }} onClick={handleWeightSave}
                  style={{ background:weightSaved?'#1a3a1a':'#A78BFA',color:weightSaved?'#6BFF9E':'#000',border:'none',borderRadius:12,padding:'10px 18px',fontWeight:900,fontSize:13,cursor:'pointer',whiteSpace:'nowrap' }}>
                  {weightSaved?'✓ Saved!':'Log'}
                </motion.button>
              </div>
              {weightLog.length>0&&(
                <div style={{ marginTop:12 }}>
                  {weightLog.slice(-5).reverse().map((e,i)=>(
                    <div key={i} style={{ display:'flex',justifyContent:'space-between',padding:'5px 0',borderBottom:i<Math.min(weightLog.length,5)-1?'1px solid #1a1a1a':'none' }}>
                      <div style={{ fontSize:11,color:'#555' }}>{e.date}</div>
                      <div style={{ fontSize:11,fontWeight:700,color:'#A78BFA' }}>{e.weight} kg</div>
                    </div>
                  ))}
                </div>
              )}
            </motion.div>
            <div style={{ background:'#111',borderRadius:18,padding:16,border:'1px solid #1a1a1a' }}>
              <div style={{ fontSize:11,color:'#444',letterSpacing:1,marginBottom:14,textTransform:'uppercase' }}>Daily Steps</div>
              {fitData.steps.weeklyData.map((steps,i)=>(
                <div key={i} style={{ display:'flex',alignItems:'center',gap:10,marginBottom:10,paddingBottom:10,borderBottom:i<6?'1px solid #1a1a1a':'none' }}>
                  <div style={{ width:28,fontSize:11,color:i===6?'#E8FF6B':'#444',fontWeight:i===6?700:400 }}>{['M','T','W','T','F','S','S'][i]}</div>
                  <div style={{ flex:1 }}>
                    <div style={{ background:'#1a1a1a',borderRadius:4,height:5,overflow:'hidden' }}>
                      <motion.div initial={{ width:0 }} animate={{ width:`${(steps/maxSteps)*100}%` }} transition={{ delay:i*0.05,duration:0.6 }} style={{ background:'#E8FF6B',height:5,borderRadius:4 }}/>
                    </div>
                    <div style={{ fontSize:10,color:'#333',marginTop:3 }}>{steps>0?steps.toLocaleString()+' steps':'No data'}</div>
                  </div>
                  <div style={{ fontSize:10,fontWeight:700,color:'#444' }}>{Math.round((steps/fitData.steps.goal)*100)}%</div>
                </div>
              ))}
            </div>
          </motion.div>
        )}

        {/* BOARD */}
        {currentView==='board'&&(
          <motion.div initial={{ opacity:0,y:20 }} animate={{ opacity:1,y:0 }} style={{ padding:'48px 20px 120px' }}>
            <div style={{ fontSize:22,fontWeight:900,marginBottom:4 }}>Fitness Board</div>
            <div style={{ fontSize:12,color:'#444',marginBottom:16 }}>Steps goal → 100 squares</div>
            <motion.div style={{ background:'linear-gradient(135deg,#0d2a1a,#0a1a0a)',borderRadius:22,padding:20,marginBottom:14,border:'1px solid #22c55e22' }}>
              <div style={{ display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:12 }}>
                <div>
                  <div style={{ fontSize:10,color:'#444',letterSpacing:1,textTransform:'uppercase' }}>Position</div>
                  <div style={{ fontSize:52,fontWeight:900,color:'#E8FF6B',lineHeight:1 }}>#{boardPos}</div>
                  <div style={{ fontSize:10,color:'#444',marginTop:4 }}>of 100 squares</div>
                </div>
                <div style={{ textAlign:'right' }}>
                  <div style={{ fontSize:10,color:'#444' }}>Next milestone</div>
                  <div style={{ fontSize:22,fontWeight:900,color:'#22c55e' }}>Sq {[25,50,75,100].find(m=>m>boardPos)||100} ⚡</div>
                </div>
              </div>
              <div style={{ background:'#0a0a0a',borderRadius:8,height:8,overflow:'hidden' }}>
                <motion.div initial={{ width:0 }} animate={{ width:`${boardPos}%` }} transition={{ duration:1.2 }} style={{ height:'100%',background:'linear-gradient(90deg,#22c55e,#E8FF6B)',borderRadius:8 }}/>
              </div>
            </motion.div>
            <div style={{ background:'#111',borderRadius:18,padding:14,border:'1px solid #1a1a1a' }}>
              <div style={{ fontSize:10,color:'#444',letterSpacing:1,textTransform:'uppercase',marginBottom:12 }}>100 Squares</div>
              <div style={{ display:'grid',gridTemplateColumns:'repeat(10,1fr)',gap:3 }}>
                {Array.from({length:100}).map((_,i)=>{
                  const sq=i+1; const isPlayer=sq===boardPos; const isPast=sq<boardPos; const isMilestone=[25,50,75,100].includes(sq);
                  return (
                    <motion.div key={i} initial={{ opacity:0,scale:0 }} animate={{ opacity:1,scale:1 }} transition={{ delay:i*0.005 }}
                      style={{ aspectRatio:'1',borderRadius:4,fontSize:7,display:'flex',alignItems:'center',justifyContent:'center', background:isPlayer?'#E8FF6B':isPast?'#E8FF6B22':isMilestone?'#f59e0b22':'#1a1a1a', border:`1px solid ${isPlayer?'#E8FF6B':isPast?'#E8FF6B44':isMilestone?'#f59e0b44':'#222'}`, color:isPlayer?'#1a1a00':isPast?'#E8FF6B88':'#333', fontWeight:isPlayer?900:400, boxShadow:isPlayer?'0 0 10px #E8FF6B88':'none' }}>
                      {isPlayer?'👤':isMilestone?'⭐':sq}
                    </motion.div>
                  );
                })}
              </div>
            </div>
          </motion.div>
        )}

        {/* JOURNAL */}
        {currentView==='journal'&&(
          <motion.div initial={{ opacity:0,y:20 }} animate={{ opacity:1,y:0 }} style={{ padding:'48px 20px 120px' }}>
            <div style={{ display:'flex',justifyContent:'space-between',alignItems:'flex-start',marginBottom:6 }}>
              <div>
                <div style={{ fontSize:22,fontWeight:900 }}>Daily Journal</div>
                <div style={{ fontSize:11,color:'#444',marginTop:2 }}>{journals.length} entries · {autoCount} auto</div>
              </div>
              <motion.button onClick={()=>{ playSound('click'); setShowJournalForm(f=>!f); }} whileTap={{ scale:0.95 }}
                style={{ background:showJournalForm?'#222':'#E8FF6B',color:showJournalForm?'#fff':'#1a1a00',border:'none',padding:'8px 14px',borderRadius:12,fontSize:11,fontWeight:700,cursor:'pointer' }}>
                {showJournalForm?'✕ Cancel':'✍️ Write'}
              </motion.button>
            </div>
            <AnimatePresence>
              {showJournalForm&&(
                <motion.div initial={{ opacity:0,height:0 }} animate={{ opacity:1,height:'auto' }} exit={{ opacity:0,height:0 }}
                  style={{ background:'#111',borderRadius:20,padding:16,marginBottom:14,border:'1px solid #E8FF6B33',overflow:'hidden' }}>
                  <div style={{ display:'flex',gap:8,marginBottom:14,flexWrap:'wrap' }}>
                    {MOODS.map(m=>(<motion.button key={m} onClick={()=>setSelectedMood(m)} whileTap={{ scale:0.9 }} style={{ fontSize:24,background:selectedMood===m?'#E8FF6B22':'#0a0a0a',border:`1px solid ${selectedMood===m?'#E8FF6B':'#222'}`,borderRadius:10,padding:'6px 8px',cursor:'pointer' }}>{m}</motion.button>))}
                  </div>
                  <textarea placeholder="Aaj kya feel hua?" value={journalText} onChange={e=>setJournalText(e.target.value)}
                    style={{ width:'100%',padding:12,marginBottom:10,background:'#0a0a0a',border:'1px solid #1a1a1a',borderRadius:12,color:'#fff',minHeight:110,fontFamily:'inherit',resize:'vertical',fontSize:14,lineHeight:1.6,boxSizing:'border-box' }}/>
                  <motion.button onClick={addJournal} whileTap={{ scale:0.97 }}
                    style={{ width:'100%',background:'#E8FF6B',color:'#1a1a00',border:'none',padding:14,borderRadius:12,fontWeight:800,fontSize:14,cursor:'pointer' }}>
                    💾 Save Entry
                  </motion.button>
                </motion.div>
              )}
            </AnimatePresence>
            {journals.length>0&&(
              <div style={{ display:'flex',gap:6,overflowX:'auto',marginBottom:14,paddingBottom:4,scrollbarWidth:'none' }}>
                {['all',...journalDates.slice(0,7)].map(d=>(
                  <motion.button key={d} onClick={()=>setJournalFilter(d)} whileTap={{ scale:0.95 }}
                    style={{ background:journalFilter===d?'#E8FF6B':'#111',color:journalFilter===d?'#1a1a00':'#444',border:`1px solid ${journalFilter===d?'#E8FF6B':'#1a1a1a'}`,borderRadius:20,padding:'5px 12px',fontSize:10,fontWeight:700,cursor:'pointer',whiteSpace:'nowrap',flexShrink:0 }}>
                    {d==='all'?`All (${journals.length})`:d.split(',')[0]}
                  </motion.button>
                ))}
              </div>
            )}
            {filteredJournals.length===0?(
              <div style={{ textAlign:'center',color:'#333',padding:'40px 20px' }}><div style={{ fontSize:40,marginBottom:12 }}>📖</div><div style={{ fontSize:14,color:'#555' }}>Koi entry nahi.</div></div>
            ):filteredJournals.map((j,idx)=>(
              <motion.div key={j.id} initial={{ opacity:0,y:10 }} animate={{ opacity:1,y:0 }} transition={{ delay:idx*0.04 }}
                style={{ background:'#111',borderRadius:18,padding:16,marginBottom:10,border:`1px solid ${j.autoGenerated?'#22c55e22':'#1a1a1a'}` }}>
                <div style={{ display:'flex',justifyContent:'space-between',alignItems:'flex-start',marginBottom:10 }}>
                  <div style={{ display:'flex',gap:10,alignItems:'center' }}>
                    <div style={{ fontSize:26 }}>{j.mood}</div>
                    <div>
                      <div style={{ fontSize:12,fontWeight:700,color:'#E8FF6B' }}>{j.date}</div>
                      <div style={{ fontSize:10,color:'#333',marginTop:1 }}>{j.time}</div>
                      {j.autoGenerated&&<div style={{ fontSize:9,color:'#22c55e',marginTop:2 }}>🤖 Auto</div>}
                    </div>
                  </div>
                  <motion.button onClick={()=>deleteJournal(j.id)} whileTap={{ scale:0.9 }} style={{ background:'transparent',color:'#333',border:'1px solid #222',padding:'3px 8px',borderRadius:8,fontSize:10,cursor:'pointer' }}>🗑️</motion.button>
                </div>
                <div style={{ fontSize:13,color:'#aaa',lineHeight:1.7 }}>{j.text}</div>
              </motion.div>
            ))}
          </motion.div>
        )}
{currentView === 'predictor' && <BodyPredictor />}
{currentView === 'coach' && <AiCoach />}
{currentView === 'pr' && <PRTracker />}
{currentView === 'bmi' && <BMICalculator />}
{currentView === 'measurements' && <BodyMeasurements />}
        {currentView==='sleep'&&(
          <motion.div initial={{ opacity:0,y:20 }} animate={{ opacity:1,y:0 }} style={{ padding:'48px 20px 120px' }}>
            <div style={{ fontSize:22,fontWeight:900,marginBottom:4 }}>Sleep Quality</div>
            <div style={{ fontSize:12,color:'#444',marginBottom:16 }}>Google Fit · Real Sleep Stages</div>
            {(()=>{
              const avgScore=Math.round(sleepStages.reduce((a,b)=>a+b.qualityScore,0)/sleepStages.length);
              const meta=sleepQualityMeta(avgScore);
              const avgHrs=(sleepStages.reduce((a,b)=>a+b.totalHours,0)/sleepStages.length).toFixed(1);
              return (
                <motion.div style={{ background:'linear-gradient(135deg,#0d0b1e,#120d25)',borderRadius:24,padding:22,border:'1px solid #4C6EF522',marginBottom:16 }}>
                  <div style={{ display:'flex',alignItems:'center',gap:20 }}>
                    <div style={{ position:'relative',width:96,height:96,flexShrink:0 }}>
                      <svg viewBox="0 0 100 100" style={{ width:96,height:96,transform:'rotate(-90deg)' }}>
                        <circle cx="50" cy="50" r="42" fill="none" stroke="#1a1a2e" strokeWidth="10"/>
                        <motion.circle cx="50" cy="50" r="42" fill="none" stroke={meta.color} strokeWidth="10" strokeDasharray="263.9" strokeLinecap="round" initial={{ strokeDashoffset:263.9 }} animate={{ strokeDashoffset:263.9-(avgScore/100)*263.9 }} transition={{ duration:1.2,delay:0.3 }}/>
                      </svg>
                      <div style={{ position:'absolute',top:'50%',left:'50%',transform:'translate(-50%,-50%)',textAlign:'center' }}>
                        <div style={{ fontSize:22,fontWeight:900,color:meta.color }}>{avgScore}</div>
                        <div style={{ fontSize:8,color:'#444' }}>score</div>
                      </div>
                    </div>
                    <div>
                      <div style={{ fontSize:10,color:'#444',letterSpacing:2,textTransform:'uppercase',marginBottom:4 }}>7-Night Avg</div>
                      <div style={{ fontSize:26,fontWeight:900,color:meta.color }}>{meta.label}</div>
                      <div style={{ fontSize:13,color:'#666',marginTop:4 }}>{avgHrs}h avg sleep</div>
                    </div>
                  </div>
                </motion.div>
              );
            })()}
            <div style={{ fontSize:10,color:'#444',letterSpacing:1,textTransform:'uppercase',marginBottom:10 }}>Nightly Breakdown</div>
            {sleepStages.map((night,i)=>{
              const meta=sleepQualityMeta(night.qualityScore);
              const totalMin=night.stages.reduce((a,s)=>a+s.minutes,0);
              const isSelected=selectedNight?.date===night.date;
              return (
                <motion.div key={i} initial={{ opacity:0,y:10 }} animate={{ opacity:1,y:0 }} transition={{ delay:i*0.05 }}
                  onClick={()=>{ playSound('click'); setSelectedNight(isSelected?null:night); }}
                  style={{ background:'#111',borderRadius:16,padding:'14px 16px',marginBottom:8,border:`1px solid ${isSelected?'#4C6EF544':'#1a1a1a'}`,cursor:'pointer' }}>
                  <div style={{ display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:10 }}>
                    <div style={{ display:'flex',alignItems:'center',gap:10 }}>
                      <div style={{ width:34,height:34,borderRadius:10,background:'#1a1a2e',display:'flex',alignItems:'center',justifyContent:'center',fontSize:16 }}>🌙</div>
                      <div>
                        <div style={{ fontSize:13,fontWeight:700 }}>{night.date}</div>
                        <div style={{ fontSize:11,color:'#444' }}>{night.totalHours}h total</div>
                      </div>
                    </div>
                    <div style={{ textAlign:'right' }}>
                      <div style={{ fontSize:20,fontWeight:900,color:meta.color }}>{night.qualityScore}</div>
                      <div style={{ fontSize:9,color:meta.color }}>{meta.label}</div>
                    </div>
                  </div>
                  <div style={{ display:'flex',borderRadius:5,overflow:'hidden',height:7 }}>
                    {night.stages.map(stage=>(
                      <motion.div key={stage.stage} initial={{ width:0 }} animate={{ width:totalMin>0?`${(stage.minutes/totalMin)*100}%`:'0%' }} transition={{ delay:0.2+i*0.05,duration:0.6 }} style={{ background:stage.color,height:'100%' }}/>
                    ))}
                  </div>
                  <AnimatePresence>
                    {isSelected&&(
                      <motion.div initial={{ opacity:0,height:0 }} animate={{ opacity:1,height:'auto' }} exit={{ opacity:0,height:0 }} style={{ marginTop:14,paddingTop:14,borderTop:'1px solid #1a1a1a',overflow:'hidden' }}>
                        <div style={{ display:'grid',gridTemplateColumns:'1fr 1fr',gap:8 }}>
                          {night.stages.map(stage=>(
                            <div key={stage.stage} style={{ background:'#0a0a0a',borderRadius:10,padding:'10px 12px',display:'flex',alignItems:'center',gap:10 }}>
                              <div style={{ width:10,height:10,borderRadius:3,background:stage.color,flexShrink:0 }}/>
                              <div>
                                <div style={{ fontSize:14,fontWeight:800,color:stage.color }}>{stage.minutes>=60?`${Math.floor(stage.minutes/60)}h ${stage.minutes%60}m`:`${stage.minutes}m`}</div>
                                <div style={{ fontSize:9,color:'#444' }}>{stage.label} · {totalMin>0?Math.round((stage.minutes/totalMin)*100):0}%</div>
                              </div>
                            </div>
                          ))}
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </motion.div>
              );
            })}
          </motion.div>
        )}

        {/* PROFILE */}
        {currentView==='profile'&&(
          <motion.div initial={{ opacity:0,y:20 }} animate={{ opacity:1,y:0 }} style={{ padding:'48px 20px 120px' }}>
            <div style={{ fontSize:22,fontWeight:900,marginBottom:16 }}>My Profile</div>
            {userProfile ? (
              <>
                <div style={{ background:'#1A1A1A',borderRadius:24,padding:24,border:'1px solid #222',marginBottom:14 }}>
                  <div style={{ width:64,height:64,borderRadius:20,background:'#E8FF6B',display:'flex',alignItems:'center',justifyContent:'center',fontSize:28,marginBottom:14 }}>💪</div>
                  <div style={{ fontSize:24,fontWeight:900,color:'#fff',marginBottom:4 }}>{userProfile.name}</div>
                  <div style={{ fontSize:13,color:'#555' }}>Age: {userProfile.age} yrs</div>
                  <div style={{ display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,marginTop:16 }}>
                    {[['⚖️ Weight',`${userProfile.weight} ${userProfile.weightUnit}`],['📏 Height',`${userProfile.height} ${userProfile.heightUnit}`],['🎯 Goal',goalLabel[userProfile.fitnessGoal]||userProfile.fitnessGoal],['🏅 Level',levelLabel[userProfile.fitnessLevel]||userProfile.fitnessLevel]].map(([label,val],i)=>(
                      <div key={i} style={{ background:'#111',borderRadius:14,padding:'12px 14px',border:'1px solid #1a1a1a' }}>
                        <div style={{ fontSize:10,color:'#444',marginBottom:4 }}>{label}</div>
                        <div style={{ fontSize:14,fontWeight:700,color:'#E8FF6B' }}>{val}</div>
                      </div>
                    ))}
                  </div>
                </div>
                <motion.button onClick={()=>setShowProfileSetup(true)} whileTap={{ scale:0.97 }}
                  style={{ width:'100%',background:'#E8FF6B',color:'#1a1a00',border:'none',padding:16,borderRadius:16,fontWeight:800,fontSize:15,cursor:'pointer',marginBottom:10 }}>
                  ✏️ Edit Profile
                </motion.button>
                <motion.button onClick={handleSignOut} whileTap={{ scale:0.97 }}
                  style={{ width:'100%',background:'#111',color:'#FF6B6B',border:'1px solid #FF6B6B22',padding:16,borderRadius:16,fontWeight:700,fontSize:14,cursor:'pointer' }}>
                  🔓 Sign Out
                </motion.button>
              </>
            ):(
              <div style={{ textAlign:'center',padding:'40px 20px' }}>
                <div style={{ fontSize:40,marginBottom:12 }}>👤</div>
                <motion.button onClick={()=>setShowProfileSetup(true)} whileTap={{ scale:0.97 }}
                  style={{ background:'#E8FF6B',color:'#1a1a00',border:'none',padding:'14px 28px',borderRadius:16,fontWeight:800,fontSize:15,cursor:'pointer' }}>
                  Setup Profile
                </motion.button>
              </div>
            )}
          </motion.div>
        )}

        {/* BOTTOM NAV */}
        <div style={{ position:'fixed',bottom:0,left:0,right:0,background:'#111',borderTop:'1px solid #1a1a1a',maxWidth:390,margin:'0 auto',display:'flex',justifyContent:'space-around',padding:'10px 0 18px',zIndex:100 }}>
          {NAV_ITEMS.map(nav=>{
            const active=currentView===nav.id;
            return (
              <motion.button key={nav.id} onClick={()=>handleNav(nav.id)} whileTap={{ scale:0.88 }}
                style={{ background:'none',border:'none',color:active?'#E8FF6B':'#444',display:'flex',flexDirection:'column',alignItems:'center',gap:3,cursor:'pointer',padding:'6px 10px',fontSize:8,fontWeight:active?800:400,position:'relative' }}>
                <motion.div animate={active?{ scale:1.15,y:-3 }:{ scale:1,y:0 }}
                  style={{ width:active?38:32,height:active?38:32,borderRadius:12,background:active?'#E8FF6B':'#1a1a1a',display:'flex',alignItems:'center',justifyContent:'center',fontSize:16,boxShadow:active?'0 0 16px #E8FF6B55':'none' }}>
                  {nav.icon}
                </motion.div>
                <span style={{ letterSpacing:0.5 }}>{nav.label}</span>
                {nav.id==='journal'&&autoCount>0&&(<div style={{ position:'absolute',top:4,right:6,width:7,height:7,borderRadius:'50%',background:'#22c55e',border:'1px solid #0D0D0D' }}/>)}
                {nav.id==='train'&&todayWorkout&&(<div style={{ position:'absolute',top:4,right:6,width:7,height:7,borderRadius:'50%',background:'#E8FF6B',border:'1px solid #0D0D0D' }}/>)}
              </motion.button>
            );
          })}
          <motion.button onClick={()=>handleNav('profile')} whileTap={{ scale:0.88 }}
            style={{ background:'none',border:'none',color:currentView==='profile'?'#E8FF6B':'#444',display:'flex',flexDirection:'column',alignItems:'center',gap:3,cursor:'pointer',padding:'6px 10px',fontSize:8,fontWeight:currentView==='profile'?800:400 }}>
            <motion.div animate={currentView==='profile'?{ scale:1.15,y:-3 }:{ scale:1,y:0 }}
              style={{ width:currentView==='profile'?38:32,height:currentView==='profile'?38:32,borderRadius:12,background:currentView==='profile'?'#E8FF6B':'#1a1a1a',display:'flex',alignItems:'center',justifyContent:'center',fontSize:16,boxShadow:currentView==='profile'?'0 0 16px #E8FF6B55':'none' }}>
              👤
            </motion.div>
            <span style={{ letterSpacing:0.5 }}>ME</span>
          </motion.button>
        </div>
      </div>
    </>
  );
}